--[[
This file is part of the mod inserter-fuel-leech that is licensed under
the GNU GPL-3.0. See the file COPYING for a copy of the GNU GPLv3.0.
]]
data:extend({
    {
        name = "inserter-fuel-leech-inserters-enabled",
        type = "string-setting",
        order = "011",
        setting_type = "runtime-global",
        allowed_values = {"none", "itemfueled", "all"},
        default_value = "all",
    },
    {
        name = "inserter-fuel-leech-self-leech-from-drop-enabled",
        type = "bool-setting",
        order = "012",
        setting_type = "runtime-global",
        default_value = true,
    },
    {
        name = "inserter-fuel-leech-self-refuel-cheat-enabled",
        type = "bool-setting",
        order = "013",
        setting_type = "runtime-global",
        default_value = true,
    },
    {
        name = "inserter-fuel-leech-target-item-count-min",
        type = "int-setting",
        order = "015",
        setting_type = "runtime-global",
        minimum_value = 1,
        maximum_value = 100000,
        default_value = 5,
    },
    {
        name = "inserter-fuel-leech-pickup-margin-ticks",
        type = "int-setting",
        order = "021",
        setting_type = "runtime-global",
        minimum_value = 1,
        maximum_value = 60,
        default_value = 3,
    },
    {
        name = "inserter-fuel-leech-no-use-for-fuel-seconds-to-wait",
        type = "double-setting",
        order = "022",
        setting_type = "runtime-global",
        minimum_value = 1,
        maximum_value = 600,
        default_value = 30,
    },
    {
        name = "inserter-fuel-leech-missing-resource-seconds-to-wait",
        type = "double-setting",
        order = "023",
        setting_type = "runtime-global",
        minimum_value = 1,
        maximum_value = 600,
        default_value = 10,
    },
    {
        name = "inserter-fuel-leech-missing-power-seconds-to-wait",
        type = "double-setting",
        order = "024",
        setting_type = "runtime-global",
        minimum_value = 1,
        maximum_value = 600,
        default_value = 10,
    },
    {
        name = "inserter-fuel-leech-vanilla-self-refuel-seconds-to-wait",
        type = "double-setting",
        order = "025",
        setting_type = "runtime-global",
        minimum_value = 1,
        maximum_value = 600,
        default_value = 2,
    },
    {
        name = "inserter-fuel-leech-wait-variation-seconds",
        type = "double-setting",
        order = "030",
        setting_type = "runtime-global",
        minimum_value = 0,
        maximum_value = 60,
        default_value = 3,
    },
    {
        name = "inserter-fuel-leech-discover-per-tick",
        type = "int-setting",
        order = "050",
        setting_type = "runtime-global",
        minimum_value = 0,
        maximum_value = 1000000,
        default_value = 1,
    },
    {
        name = "inserter-fuel-leech-discover-empty-chunks-per-tick",
        type = "int-setting",
        order = "051",
        setting_type = "runtime-global",
        minimum_value = 1,
        maximum_value = 1000000,
        default_value = 10,
    },

    {
        name = "inserter-fuel-leech-chat-log-color",
        type = "color-setting",
        order = "300",
        setting_type = "runtime-per-user",
        default_value = {0.75, 0.75, 0.75, 1.0},
    },
    {
        name = "inserter-fuel-leech-log-low-traffic",
        type = "bool-setting",
        order = "310",
        setting_type = "runtime-per-user",
        default_value = false,
    },
    {
        name = "inserter-fuel-leech-log-discovery-cycle",
        type = "bool-setting",
        order = "320",
        setting_type = "runtime-per-user",
        default_value = false,
    },
    {
        name = "inserter-fuel-leech-watch-last-inserter",
        type = "bool-setting",
        order = "330",
        setting_type = "runtime-per-user",
        default_value = false,
    },
    {
        name = "inserter-fuel-leech-last-inserter-log-color",
        type = "color-setting",
        order = "340",
        setting_type = "runtime-per-user",
        default_value = {0.75, 0.75, 0.75, 1.0},
    },
})
