---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaActiveTriggerPrototype
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Prototype of an Active Trigger.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaActiveTriggerPrototype.html)
---@class LuaActiveTriggerPrototype:LuaPrototypeBase
---The chance that a new fork will spawn after each jump \[0,1]. default = 0.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaActiveTriggerPrototype.html#fork_chance)
---@field fork_chance double
---The tick delay between each jump. 0 = all jumps instantaneous. default = 0.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaActiveTriggerPrototype.html#jump_delay_ticks)
---@field jump_delay_ticks uint
---maximum number of forks allowed to spawn for the entire chain. default = infinity.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaActiveTriggerPrototype.html#max_forks)
---@field max_forks uint
---The maximum number of forks that can spawn from a single jump. default = 1.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaActiveTriggerPrototype.html#max_forks_per_jump)
---@field max_forks_per_jump uint
---The max number of jumps per trigger. default = 5.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaActiveTriggerPrototype.html#max_jumps)
---@field max_jumps uint
---The max distance jumps are allowed to travel away from the original target. default = infinity.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaActiveTriggerPrototype.html#max_range)
---@field max_range double
---The max length of jumps. default = 5.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaActiveTriggerPrototype.html#max_range_per_jump)
---@field max_range_per_jump double
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaActiveTriggerPrototype.html#object_name)
---@field object_name string
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaActiveTriggerPrototype.html#valid)
---@field valid boolean
local LuaActiveTriggerPrototype={
}
end

