---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaBurnerPrototype
-- This file is automatically generated. Edits will be overwritten without warning.

do
---@class LuaBurnerPrototype.light_flicker
---@field minimum_intensity float
---@field maximum_intensity float
---@field derivation_change_frequency float
---@field derivation_change_deviation float
---@field border_fix_speed float
---@field minimum_light_size float
---@field light_intensity_to_size_coefficient float
---@field color Color
local LuaBurnerPrototype_light_flicker={
}
end

do
---Prototype of a burner energy source.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaBurnerPrototype.html)
---@class LuaBurnerPrototype:LuaObject
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaBurnerPrototype.html#burnt_inventory_size)
---@field burnt_inventory_size uint
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaBurnerPrototype.html#effectivity)
---@field effectivity double
---The table of emissions of this energy source in `pollution/Joule`, indexed by pollutant type. Multiplying it by energy consumption in `Watt` gives `pollution/second`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaBurnerPrototype.html#emissions_per_joule)
---@field emissions_per_joule {[string]:double}
---The value in the dictionary is meaningless and exists just to allow for easy lookup.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaBurnerPrototype.html#fuel_categories)
---@field fuel_categories {[string]:true}
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaBurnerPrototype.html#fuel_inventory_size)
---@field fuel_inventory_size uint
---The light flicker definition for this burner prototype.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaBurnerPrototype.html#light_flicker)
---@field light_flicker? LuaBurnerPrototype.light_flicker
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaBurnerPrototype.html#object_name)
---@field object_name string
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaBurnerPrototype.html#render_no_network_icon)
---@field render_no_network_icon boolean
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaBurnerPrototype.html#render_no_power_icon)
---@field render_no_power_icon boolean
---The smoke sources for this burner prototype.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaBurnerPrototype.html#smoke)
---@field smoke? (SmokeSource)[]
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaBurnerPrototype.html#valid)
---@field valid boolean
local LuaBurnerPrototype={
}
end

