---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaCombinatorControlBehavior
-- This file is automatically generated. Edits will be overwritten without warning.

do
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaCombinatorControlBehavior.html)
---@class LuaCombinatorControlBehavior:LuaControlBehavior
---The circuit network signals sent by this combinator last tick.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaCombinatorControlBehavior.html#signals_last_tick)
---@field signals_last_tick (Signal)[]
local LuaCombinatorControlBehavior={
---Gets the value of a specific signal sent by this combinator behavior last tick or `nil` if the signal didn't exist.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaCombinatorControlBehavior.html#get_signal_last_tick)
---@param signal SignalID The signal to get
---@return int? 
get_signal_last_tick = function(signal) end;
}
end

