---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaChunkIterator
-- This file is automatically generated. Edits will be overwritten without warning.

do
---A chunk iterator can be used for iterating chunks coordinates of a surface.
---
---The returned type is a [ChunkPositionAndArea](https://lua-api.factorio.com/latest/concepts.html#ChunkPositionAndArea) containing the chunk coordinates and its area.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaChunkIterator.html)
---
---### Example
---
---```
---for chunk in some_surface.get_chunks() do
---  game.player.print("x: " .. chunk.x .. ", y: " .. chunk.y)
---  game.player.print("area: " .. serpent.line(chunk.area))
---end
---```
---@class LuaChunkIterator:LuaObject
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaChunkIterator.html#object_name)
---@field object_name string
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaChunkIterator.html#valid)
---@field valid boolean
---Gets the next chunk position if the iterator is not yet done and increments the it.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaChunkIterator.html#call_operator)
---@overload fun():ChunkPositionAndArea
local LuaChunkIterator={
}
end

