---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaCircuitNetwork
-- This file is automatically generated. Edits will be overwritten without warning.

do
---A circuit network associated with a given entity, connector, and wire type.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaCircuitNetwork.html)
---@class LuaCircuitNetwork:LuaObject
---The number of circuits connected to this network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaCircuitNetwork.html#connected_circuit_count)
---@field connected_circuit_count uint
---The entity this circuit network reference is associated with.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaCircuitNetwork.html#entity)
---@field entity LuaEntity
---The circuit networks ID.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaCircuitNetwork.html#network_id)
---@field network_id uint
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaCircuitNetwork.html#object_name)
---@field object_name string
---The circuit network signals last tick. `nil` if there were no signals last tick.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaCircuitNetwork.html#signals)
---@field signals? (Signal)[]
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaCircuitNetwork.html#valid)
---@field valid boolean
---Wire connector ID on associated entity this network was gotten from.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaCircuitNetwork.html#wire_connector_id)
---@field wire_connector_id defines.wire_connector_id
---The wire type this network is associated with.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaCircuitNetwork.html#wire_type)
---@field wire_type defines.wire_type
local LuaCircuitNetwork={
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaCircuitNetwork.html#get_signal)
---@param signal SignalID The signal to read.
---@return int  #The current value of the signal.
get_signal = function(signal) end;
}
end

