---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaControlBehavior
-- This file is automatically generated. Edits will be overwritten without warning.

do
---The control behavior for an entity. Inserters have logistic network and circuit network behavior logic, lamps have circuit logic and so on. This is an abstract base class that concrete control behaviors inherit.
---
---An control reference becomes invalid once the control behavior is removed or the entity (see [LuaEntity](https://lua-api.factorio.com/latest/classes/LuaEntity.html)) it resides in is destroyed.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaControlBehavior.html)
---@class LuaControlBehavior:LuaObject
---The entity this control behavior belongs to.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaControlBehavior.html#entity)
---@field entity LuaEntity
---The concrete type of this control behavior.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaControlBehavior.html#type)
---@field type defines.control_behavior.type
local LuaControlBehavior={
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaControlBehavior.html#get_circuit_network)
---@param wire_connector_id defines.wire_connector_id Wire connector to get circuit network for.
---@return LuaCircuitNetwork?  #The circuit network or nil.
get_circuit_network = function(wire_connector_id) end;
}
end

