---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaContainerControlBehavior
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Control behavior for container entities.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaContainerControlBehavior.html)
---@class LuaContainerControlBehavior:LuaControlBehavior
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaContainerControlBehavior.html#object_name)
---@field object_name string
---`true` if this container is sending its content to a circuit network
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaContainerControlBehavior.html#read_contents)
---@field read_contents boolean
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaContainerControlBehavior.html#valid)
---@field valid boolean
local LuaContainerControlBehavior={
}
end

