---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaDecorativePrototype
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Prototype of an optimized decorative.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaDecorativePrototype.html)
---@class LuaDecorativePrototype:LuaPrototypeBase
---Autoplace specification for this decorative prototype, if any.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaDecorativePrototype.html#autoplace_specification)
---@field autoplace_specification? AutoplaceSpecification
---The bounding box used for collision checking.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaDecorativePrototype.html#collision_box)
---@field collision_box BoundingBox
---The collision masks this decorative uses
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaDecorativePrototype.html#collision_mask)
---@field collision_mask CollisionMask
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaDecorativePrototype.html#decal)
---@field decal boolean
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaDecorativePrototype.html#grows_through_rail_path)
---@field grows_through_rail_path boolean
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaDecorativePrototype.html#minimal_separation)
---@field minimal_separation double
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaDecorativePrototype.html#object_name)
---@field object_name string
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaDecorativePrototype.html#placed_effect)
---@field placed_effect? (TriggerEffectItem)[]
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaDecorativePrototype.html#render_layer)
---@field render_layer string
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaDecorativePrototype.html#target_count)
---@field target_count uint
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaDecorativePrototype.html#trigger_effect)
---@field trigger_effect? (TriggerEffectItem)[]
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaDecorativePrototype.html#valid)
---@field valid boolean
local LuaDecorativePrototype={
}
end

