---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaEquipmentGrid
-- This file is automatically generated. Edits will be overwritten without warning.

do
---@class LuaEquipmentGrid.can_move_param
---The equipment to move
---@field equipment LuaEquipment
---Where to put it
---@field position EquipmentPosition
local LuaEquipmentGrid_can_move_param={
}
end

do
---@class LuaEquipmentGrid.move_param
---The equipment to move
---@field equipment LuaEquipment
---Where to put it
---@field position EquipmentPosition
local LuaEquipmentGrid_move_param={
}
end

do
---@class LuaEquipmentGrid.put_param
---Equipment prototype name
---@field name EquipmentID
---The quality, `nil` for any or if not provided `normal` is used.
---@field quality? QualityID
---Grid position to put the equipment in.
---@field position? EquipmentPosition
---If provided the action is done 'as' this player and [on\_player\_placed\_equipment](https://lua-api.factorio.com/latest/events.html#on_player_placed_equipment) is triggered.
---@field by_player? PlayerIdentification
---If true, place the equipment as a ghost.
---@field ghost? boolean
local LuaEquipmentGrid_put_param={
}
end

do
---@class LuaEquipmentGrid.take_param
---Take the equipment that contains this position in the grid.
---@field position? EquipmentPosition
---Take this exact equipment.
---@field equipment? LuaEquipment
---If provided the action is done 'as' this player and [on\_player\_removed\_equipment](https://lua-api.factorio.com/latest/events.html#on_player_removed_equipment) is triggered.
---@field by_player? PlayerIdentification
local LuaEquipmentGrid_take_param={
}
end

do
---An equipment grid is for example the inside of a power armor.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html)
---@class LuaEquipmentGrid:LuaObject
---The total energy stored in all batteries in the equipment grid.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#available_in_batteries)
---@field available_in_batteries double
---Total energy storage capacity of all batteries in the equipment grid.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#battery_capacity)
---@field battery_capacity double
---The entity that this equipment grid is owned by (in some inventory or item stack.)
---
---If the owning entity is a character owned by some player and the player is disconnected this will return `nil`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#entity_owner)
---@field entity_owner? LuaEntity
---All the equipment in this grid.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#equipment)
---@field equipment (LuaEquipment)[]
---Height of the equipment grid.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#height)
---@field height uint
---Whether this grid's equipment movement bonus is active.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#inhibit_movement_bonus)
---@field inhibit_movement_bonus boolean
---The maximum amount of shields this equipment grid has.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#max_shield)
---@field max_shield float
---Maximum energy per tick that can be created by any solar panels in the equipment grid. Actual generated energy varies depending on the daylight levels.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#max_solar_energy)
---@field max_solar_energy double
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#object_name)
---@field object_name string
---The player that this equipment grid is owned by (in some inventory or item stack.)
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#player_owner)
---@field player_owner? LuaPlayer
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#prototype)
---@field prototype LuaEquipmentGridPrototype
---The amount of shields this equipment grid has.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#shield)
---@field shield float
---Unique identifier of this equipment grid.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#unique_id)
---@field unique_id uint
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#valid)
---@field valid boolean
---Width of the equipment grid.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#width)
---@field width uint
local LuaEquipmentGrid={
---Check whether moving an equipment would succeed.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#can_move)
---@param param LuaEquipmentGrid.can_move_param 
---@return boolean 
can_move = function(param) end;
---Cancels removal for the given equipment.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#cancel_removal)
---@param equipment LuaEquipment 
---@return boolean  #If the equipment removal was successfully cancelled.
cancel_removal = function(equipment) end;
---Clear all equipment from the grid, removing it without actually returning it.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#clear)
---@param by_player? PlayerIdentification If provided, the action is done 'as' this player and [on\_player\_removed\_equipment](https://lua-api.factorio.com/latest/events.html#on_player_removed_equipment) is triggered.
clear = function(by_player) end;
---Get the number of all or some equipment in this grid.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#count)
---@param equipment? string Prototype name of the equipment to count. If not specified, count all equipment.
---@return uint 
count = function(equipment) end;
---Find equipment by name.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#find)
---@param equipment EquipmentWithQualityID Prototype of the equipment to find.
---@param search_ghosts? boolean If ghosts inner equipment should be searched. Defaults to `false`
---@return LuaEquipment?  #The first found equipment, or `nil` if equipment could not be found.
find = function(equipment, search_ghosts) end;
---Find equipment in the Equipment Grid based off a position.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#get)
---@param position EquipmentPosition The position
---@return LuaEquipment?  #The found equipment, or `nil` if equipment could not be found at the given position.
get = function(position) end;
---Get counts of all equipment in this grid.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#get_contents)
---@return {[string]:uint}  #The counts, indexed by equipment names.
get_contents = function() end;
---Total energy per tick generated by the equipment inside this grid.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#get_generator_energy)
---@param quality? QualityID 
---@return double 
get_generator_energy = function(quality) end;
---Move an equipment within this grid.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#move)
---@param param LuaEquipmentGrid.move_param 
---@return boolean  #`true` if the equipment was successfully moved.
move = function(param) end;
---Marks the given equipment for removal. If the given equipment is a ghost it is removed.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#order_removal)
---@param equipment LuaEquipment 
---@return boolean  #If the equipment was successfully marked for removal (or in the case of a ghost; removed.)
order_removal = function(equipment) end;
---Insert an equipment into the grid.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#put)
---@param param LuaEquipmentGrid.put_param 
---@return LuaEquipment?  #The newly-added equipment, or `nil` if the equipment could not be added.
put = function(param) end;
---Revives the given equipment ghost if possible.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#revive)
---@param equipment LuaEquipment The equipment ghost to revive.
---@return LuaEquipment 
revive = function(equipment) end;
---Remove an equipment from the grid.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#take)
---@param param LuaEquipmentGrid.take_param 
---@return SimpleItemStack?  #The removed equipment, or `nil` if no equipment was removed.
take = function(param) end;
---Remove all equipment from the grid.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaEquipmentGrid.html#take_all)
---@param by_player? PlayerIdentification If provided, the action is done 'as' this player and [on\_player\_removed\_equipment](https://lua-api.factorio.com/latest/events.html#on_player_removed_equipment) is triggered.
---@return (ItemCountWithQuality)[]  #List of the equipment that has been removed.
take_all = function(by_player) end;
}
end

