---@meta _

--$Factorio 2.1.20
--$Generator 1.1.47
--$Section runtime-api/LuaElectricSubNetwork
-- This file is automatically generated. Edits will be overwritten without warning.

do
---@class LuaElectricSubNetwork.get_accumulators_energy_param
---When given, only accumulators of this prototype will be considered.
---@field name? EntityID
---When given, only accumulators of this quality will be considered.
---@field quality? QualityID
local LuaElectricSubNetwork_get_accumulators_energy_param={
}
end

do
---@class LuaElectricSubNetwork.set_accumulators_energy_param
---When given, only accumulators of this prototype will be considered.
---@field name? EntityID
---When given, only accumulators of this quality will be considered.
---@field quality? QualityID
---New total energy to be set onto matching accumulators.
---@field energy double
---Whether all accumulators should have the same charge ratio, regardless of whether that means discharging some of them. Defaults to `false`.
---@field equalize? boolean
local LuaElectricSubNetwork_set_accumulators_energy_param={
}
end

do
---A LuaElectricSubNetwork represents an electricity supply group.
---
---When a supply group is related to electric poles, it spans over all poles that are connected with real (non ghost) wires and connects entities with an electric energy source in range of those poles.
---
---When a supply group is related to a global electric network, it connects entities with an electric energy source on the same surface.
---
---Implicit connections (when a power switch is closed, or when an electric pole is built on a surface with global network) do not cause supply groups to merge since they are not copper wire connections. Those connections will cause sub networks to have the same parent electric network causing electricity to be allowed to flow freely between multiple sub networks (electricity produced inside of one sub network that is connected through a power switch to a second sub network will be able to flow into a consumer connected to the second sub network).
---
---The electric sub network keeps track of connected entities. It does *not* perform electricity flow as that's the responsibility of the electric network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaElectricSubNetwork.html)
---@class LuaElectricSubNetwork:LuaObject
---Unique identifier of this electric sub network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaElectricSubNetwork.html#id)
---@field id uint32
---List of sub networks that are directly connected to this sub network through power switches or because they span over electric poles placed on a surface with global network (all poles on a surface with global network are implicitly connected to global network making their networks neighbour of a global network).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaElectricSubNetwork.html#neighbours)
---@field neighbours (LuaElectricSubNetwork)[]
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaElectricSubNetwork.html#object_name)
---@field object_name string
---Parent network to this sub network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaElectricSubNetwork.html#parent_network)
---@field parent_network LuaElectricNetwork
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaElectricSubNetwork.html#valid)
---@field valid boolean
local LuaElectricSubNetwork={
---Gets total energy stored inside of accumulators connected to the electric sub network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaElectricSubNetwork.html#get_accumulators_energy)
---@param param LuaElectricSubNetwork.get_accumulators_energy_param 
---@return EnergyAndCapacityPair 
get_accumulators_energy = function(param) end;
---Changes energy stored inside of accumulators connected to the electric sub network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaElectricSubNetwork.html#set_accumulators_energy)
---@param param LuaElectricSubNetwork.set_accumulators_energy_param 
set_accumulators_energy = function(param) end;
}
end

