---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaFluidBox
-- This file is automatically generated. Edits will be overwritten without warning.

do
---An array of fluid boxes of an entity. Entities may contain more than one fluid box, and some can change the number of fluid boxes -- for instance, an assembling machine will change its number of fluid boxes depending on its active recipe. See [Fluid](https://lua-api.factorio.com/latest/concepts.html#Fluid).
---
---Do note that reading from a [LuaFluidBox](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html) creates a new table and writing will copy the given fields from the table into the engine's own fluid box structure. Therefore, the correct way to update a fluidbox of an entity is to read it first, modify the table, then write the modified table back. Directly accessing the returned table's attributes won't have the desired effect.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html)
---
---### Example
---
---```
----- Double the temperature of the fluid in entity's first fluid box.
---fluid = entity.fluidbox[1]
---fluid.temperature = fluid.temperature * 2
---entity.fluidbox[1] = fluid
---```
---@class LuaFluidBox:LuaObject
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#object_name)
---@field object_name string
---The entity that owns this fluidbox.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#owner)
---@field owner LuaEntity
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#valid)
---@field valid boolean
---Access, set or clear a fluid box. The index must always be in bounds (see [LuaFluidBox::length\_operator](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#length_operator)). New fluidboxes may not be added or removed using this operator.
---
---Is `nil` if the given fluid box does not contain any fluid. Writing `nil` removes all fluid from the fluid box.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#index_operator)
---@field [uint] Fluid
---Number of fluid boxes.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#length_operator)
---@operator len:uint
local LuaFluidBox={
---Registers a linked connection between this entity and other entity. Because entity may have multiple fluidboxes, each with multiple connections that could be linked, a unique value for this and other linked\_connection\_id may need to be given.
---
---It may happen a linked connection is not established immediately due to crafting machines being possible to not have certain fluidboxes exposed at a given point in time, but once they appear (due to recipe changes that would use them) they will be linked. Linked connections are persisted as (this\_entity, this\_linked\_connection\_id, other\_entity, other\_linked\_connection\_id) so if a pipe connection definition's value of linked\_connection\_id changes existing connections may not restore correct connections.
---
---Every fluidbox connection that was defined in prototypes as connection\_type=="linked" may be linked to at most 1 other fluidbox. When trying to connect already used connection, previous connection will be removed.
---
---Linked connections cannot go to the same entity even if they would be part of other fluidbox.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#add_linked_connection)
---@param this_linked_connection_id uint 
---@param other_entity LuaEntity 
---@param other_linked_connection_id uint 
add_linked_connection = function(this_linked_connection_id, other_entity, other_linked_connection_id) end;
---Flushes all fluid from this fluidbox and its fluid system.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#flush)
---@param index uint 
---@param fluid? FluidID If provided, only this fluid is flushed.
---@return {[string]:float}  #The removed fluid.
flush = function(index, fluid) end;
---The capacity of the given fluidbox index.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#get_capacity)
---@param index uint 
---@return double 
get_capacity = function(index) end;
---The fluidboxes to which the fluidbox at the given index is connected.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#get_connections)
---@param index uint 
---@return (LuaFluidBox)[] 
get_connections = function(index) end;
---Get a fluid box filter
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#get_filter)
---@param index uint The index of the filter to get.
---@return FluidBoxFilter?  #The filter at the requested index, or `nil` if there isn't one.
get_filter = function(index) end;
---Gets counts of all fluids in the fluid segment. May return `nil` for fluid wagon, fluid turret's internal buffer, or a fluidbox which does not belong to a fluid segment.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#get_fluid_segment_contents)
---@param index uint 
---@return {[string]:uint}?  #The counts, indexed by fluid name.
get_fluid_segment_contents = function(index) end;
---Gets the unique ID of the fluid segment this fluid box belongs to. May return `nil` for fluid wagon, fluid turret's internal buffer or a fluidbox which does not belong to a fluid segment.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#get_fluid_segment_id)
---@param index uint 
---@return uint? 
get_fluid_segment_id = function(index) end;
---Returns other end of a linked connection.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#get_linked_connection)
---@param this_linked_connection_id uint 
---@return LuaEntity?  #Other entity to which a linked connection was made
---@return uint?  #linked\_connection\_id on other entity
get_linked_connection = function(this_linked_connection_id) end;
---Returns list of all linked connections registered for this entity.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#get_linked_connections)
---@return (FluidBoxConnectionRecord)[] 
get_linked_connections = function() end;
---Returns the fluid the fluidbox is locked onto
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#get_locked_fluid)
---@param index uint 
---@return string?  #`nil` if the fluidbox is not locked to any fluid.
get_locked_fluid = function(index) end;
---Get the fluid box's connections and associated data.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#get_pipe_connections)
---@param index uint 
---@return (PipeConnection)[] 
get_pipe_connections = function(index) end;
---The prototype of this fluidbox index. If this is used on a fluidbox of a crafting machine which due to recipe was created by merging multiple prototypes, a table of prototypes that were merged will be returned instead
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#get_prototype)
---@param index uint 
---@return (LuaFluidBoxPrototype)|((LuaFluidBoxPrototype)[]) 
get_prototype = function(index) end;
---Removes linked connection record. If connected, other end will be also removed.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#remove_linked_connection)
---@param this_linked_connection_id uint 
remove_linked_connection = function(this_linked_connection_id) end;
---Set a fluid box filter.
---
---Some entities cannot have their fluidbox filter set, notably fluid wagons and crafting machines.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBox.html#set_filter)
---@param index uint The index of the filter to set.
---@param filter (FluidBoxFilterSpec)|(nil) The filter to set. Setting `nil` clears the filter.
---@return boolean  #Whether the filter was set successfully.
set_filter = function(index, filter) end;
}
end

