---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaFluidBoxPrototype
-- This file is automatically generated. Edits will be overwritten without warning.

do
---A prototype of a fluidbox owned by some [LuaEntityPrototype](https://lua-api.factorio.com/latest/classes/LuaEntityPrototype.html).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBoxPrototype.html)
---@class LuaFluidBoxPrototype:LuaObject
---The entity that this belongs to.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBoxPrototype.html#entity)
---@field entity LuaEntityPrototype
---The filter, if any is set.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBoxPrototype.html#filter)
---@field filter? LuaFluidPrototype
---The index of this fluidbox prototype in the owning entity.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBoxPrototype.html#index)
---@field index uint
---The maximum temperature, if any is set.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBoxPrototype.html#maximum_temperature)
---@field maximum_temperature? double
---The minimum temperature, if any is set.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBoxPrototype.html#minimum_temperature)
---@field minimum_temperature? double
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBoxPrototype.html#object_name)
---@field object_name string
---The pipe connection points.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBoxPrototype.html#pipe_connections)
---@field pipe_connections (PipeConnectionDefinition)[]
---The production type.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBoxPrototype.html#production_type)
---@field production_type ("input")|("input-output")|("output")|("none")
---The render layer.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBoxPrototype.html#render_layer)
---@field render_layer string
---The secondary draw orders for the 4 possible connection directions.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBoxPrototype.html#secondary_draw_orders)
---@field secondary_draw_orders (int)[]
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBoxPrototype.html#valid)
---@field valid boolean
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaFluidBoxPrototype.html#volume)
---@field volume double
local LuaFluidBoxPrototype={
}
end

