---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaGui
-- This file is automatically generated. Edits will be overwritten without warning.

do
---The root of the GUI. This type houses the root elements, `top`, `left`, `center`,  `goal`, and `screen`, to which other elements can be added to be displayed on screen.
---
---Every player can have a different GUI state.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGui.html)
---@class LuaGui:LuaObject
---The center part of the GUI. It is a flow element.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGui.html#center)
---@field center LuaGuiElement
---The children GUI elements mapped by name <> element.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGui.html#children)
---@field children {[string]:LuaGuiElement}
---The flow used in the objectives window. It is a flow element. The objectives window is only visible when the flow is not empty or the objective text is set.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGui.html#goal)
---@field goal LuaGuiElement
---The left part of the GUI. It is a flow element inside a scroll pane element.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGui.html#left)
---@field left LuaGuiElement
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGui.html#object_name)
---@field object_name string
---The player who owns this gui.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGui.html#player)
---@field player LuaPlayer
---For showing a GUI somewhere relative to one of the game GUIs. It is an empty-widget element.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGui.html#relative)
---@field relative LuaGuiElement
---For showing a GUI somewhere on the entire screen. It is an empty-widget element.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGui.html#screen)
---@field screen LuaGuiElement
---The top part of the GUI. It is a flow element inside a scroll pane element.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGui.html#top)
---@field top LuaGuiElement
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGui.html#valid)
---@field valid boolean
local LuaGui={
}
end

