---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaGuiElement
-- This file is automatically generated. Edits will be overwritten without warning.

do
---@class LuaGuiElement_funcs
local LuaGuiElement_funcs={
---Add a new child element to this GuiElement.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#add)
---@param param LuaGuiElement.add_param 
---@return LuaGuiElement  #The GUI element that was added.
add = function(param) end;
---Inserts a string at the end or at the given index of this dropdown or listbox.
---
---*Can only be used if this is drop-down or list-box*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#add_item)
---@param string LocalisedString The text to insert.
---@param index? uint The index at which to insert the item.
add_item = function(string, index) end;
---Adds the given tab and content widgets to this tabbed pane as a new tab.
---
---*Can only be used if this is tabbed-pane*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#add_tab)
---@param tab LuaGuiElement The tab to add, must be a GUI element of type "tab".
---@param content LuaGuiElement The content to show when this tab is selected. Can be any type of GUI element.
add_tab = function(tab, content) end;
---Moves this GUI element to the "front" so it will draw over other elements.
---
---Only works for elements in [LuaGui::screen](https://lua-api.factorio.com/latest/classes/LuaGui.html#screen).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#bring_to_front)
bring_to_front = function() end;
---Remove children of this element. Any [LuaGuiElement](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html) objects referring to the destroyed elements become invalid after this operation.
---
---### Example
---
---```
---game.player.gui.top.clear()
---```
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#clear)
clear = function() end;
---Removes the items in this dropdown or listbox.
---
---*Can only be used if this is drop-down or list-box*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#clear_items)
clear_items = function() end;
---Closes the dropdown list if this is a dropdown and it is open.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#close_dropdown)
close_dropdown = function() end;
---Remove this element, along with its children. Any [LuaGuiElement](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html) objects referring to the destroyed elements become invalid after this operation.
---
---The top-level GUI elements - [LuaGui::top](https://lua-api.factorio.com/latest/classes/LuaGui.html#top), [LuaGui::left](https://lua-api.factorio.com/latest/classes/LuaGui.html#left), [LuaGui::center](https://lua-api.factorio.com/latest/classes/LuaGui.html#center) and [LuaGui::screen](https://lua-api.factorio.com/latest/classes/LuaGui.html#screen) - can't be destroyed.
---
---### Example
---
---```
---game.player.gui.top.greeting.destroy()
---```
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#destroy)
destroy = function() end;
---Focuses this GUI element if possible.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#focus)
focus = function() end;
---Forces this frame to re-auto-center. Only works on frames stored directly in [LuaGui::screen](https://lua-api.factorio.com/latest/classes/LuaGui.html#screen).
---
---**Events:**
---
---* Will raise [on\_gui\_location\_changed](https://lua-api.factorio.com/latest/events.html#on_gui_location_changed) in a future tick.
---
---*Can only be used if this is frame*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#force_auto_center)
force_auto_center = function() end;
---Gets the index that this element has in its parent element.
---
---This iterates through the children of the parent of this element, meaning this has a non-free cost to get, but is faster than doing the equivalent in Lua.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#get_index_in_parent)
---@return uint 
get_index_in_parent = function() end;
---Gets the item at the given index from this dropdown or listbox.
---
---*Can only be used if this is drop-down or list-box*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#get_item)
---@param index uint The index to get
---@return LocalisedString 
get_item = function(index) end;
---The mod that owns this Gui element or `nil` if it's owned by the scenario script.
---
---This has a not-super-expensive, but non-free cost to get.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#get_mod)
---@return string? 
get_mod = function() end;
---Returns whether this slider only allows discrete values.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#get_slider_discrete_values)
---@return boolean 
get_slider_discrete_values = function() end;
---Gets this sliders maximum value.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#get_slider_maximum)
---@return double 
get_slider_maximum = function() end;
---Gets this sliders minimum value.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#get_slider_minimum)
---@return double 
get_slider_minimum = function() end;
---Gets the minimum distance this slider can move.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#get_slider_value_step)
---@return double 
get_slider_value_step = function() end;
---Removes the item at the given index from this dropdown or listbox.
---
---*Can only be used if this is drop-down or list-box*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#remove_item)
---@param index uint The index
remove_item = function(index) end;
---Removes the given tab and its associated content from this tabbed pane.
---
---Removing a tab does not destroy the tab or the tab contents. It just removes them from the view. When removing tabs, [LuaGuiElement::selected\_tab\_index](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#selected_tab_index) needs to be manually updated.
---
---*Can only be used if this is tabbed-pane*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#remove_tab)
---@param tab? LuaGuiElement The tab to remove or `nil` to remove all tabs.
remove_tab = function(tab) end;
---Scrolls this scroll bar to the bottom.
---
---*Can only be used if this is scroll-pane or text-box*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#scroll_to_bottom)
scroll_to_bottom = function() end;
---Scrolls this scroll bar such that the specified GUI element is visible to the player.
---
---*Can only be used if this is scroll-pane*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#scroll_to_element)
---@param element LuaGuiElement The element to scroll to.
---@param scroll_mode? ("in-view")|("top-third") Where the element should be positioned in the scroll-pane. Defaults to `"in-view"`.
scroll_to_element = function(element, scroll_mode) end;
---Scrolls the scroll bar such that the specified listbox item is visible to the player.
---
---*Can only be used if this is list-box*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#scroll_to_item)
---@param index int The item index to scroll to.
---@param scroll_mode? ("in-view")|("top-third") Where the item should be positioned in the list-box. Defaults to `"in-view"`.
scroll_to_item = function(index, scroll_mode) end;
---Scrolls this scroll bar to the left.
---
---*Can only be used if this is scroll-pane or text-box*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#scroll_to_left)
scroll_to_left = function() end;
---Scrolls this scroll bar to the right.
---
---*Can only be used if this is scroll-pane or text-box*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#scroll_to_right)
scroll_to_right = function() end;
---Scrolls this scroll bar to the top.
---
---*Can only be used if this is scroll-pane or text-box*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#scroll_to_top)
scroll_to_top = function() end;
---Selects a range of text in this textbox.
---
---### Example
---
---```
----- Select the characters "amp" from "example":
---textbox.select(3, 5)
---```
---
---### Example
---
---```
----- Move the cursor to the start of the text box:
---textbox.select(1, 0)
---```
---
---*Can only be used if this is textfield or text-box*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#select)
---@param start_index int The index of the first character to select
---@param end_index int The index of the last character to select
select = function(start_index, end_index) end;
---Selects all the text in this textbox.
---
---*Can only be used if this is textfield or text-box*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#select_all)
select_all = function() end;
---Sets the given string at the given index in this dropdown or listbox.
---
---*Can only be used if this is drop-down or list-box*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#set_item)
---@param index uint The index whose text to replace.
---@param string LocalisedString The text to set at the given index.
set_item = function(index, string) end;
---Sets whether this slider only allows discrete values.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#set_slider_discrete_values)
---@param value boolean 
set_slider_discrete_values = function(value) end;
---Sets this sliders minimum and maximum values. The minimum can't be >= the maximum.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#set_slider_minimum_maximum)
---@param minimum double 
---@param maximum double 
set_slider_minimum_maximum = function(minimum, maximum) end;
---Sets the minimum distance this slider can move. The minimum distance can't be > (max - min).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#set_slider_value_step)
---@param value double 
set_slider_value_step = function(value) end;
---Swaps the children at the given indices in this element.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#swap_children)
---@param index_1 uint The index of the first child.
---@param index_2 uint The index of the second child.
swap_children = function(index_1, index_2) end;
}
end

do
---@class LuaGuiElement.add_param.base
---The kind of element to add, which potentially has its own attributes as listed below.
---@field type GuiElementType
---Name of the child element. It must be unique within the parent element.
---@field name? string
---Text displayed on the child element. For frames, this is their title. For other elements, like buttons or labels, this is the content. Whilst this attribute may be used on all elements, it doesn't make sense for tables and flows as they won't display it.
---@field caption? LocalisedString
---Tooltip of the child element.
---@field tooltip? LocalisedString
---Elem tooltip of the child element. Will be displayed above `tooltip`.
---@field elem_tooltip? ElemID
---Whether the child element is enabled. Defaults to `true`.
---@field enabled? boolean
---Whether the child element is visible. Defaults to `true`.
---@field visible? boolean
---Whether the child element is ignored by interaction. Defaults to `false`.
---@field ignored_by_interaction? boolean
---The name of the style prototype to apply to the new element.
---@field style? string
---[Tags](https://lua-api.factorio.com/latest/concepts.html#Tags) associated with the child element.
---@field tags? Tags
---Location in its parent that the child element should slot into. By default, the child will be appended onto the end.
---@field index? uint
---Where to position the child element when in the `relative` element.
---@field anchor? GuiAnchor
---How the element should interact with game controllers. Defaults to [defines.game\_controller\_interaction.normal](https://lua-api.factorio.com/latest/defines.html#defines.game_controller_interaction.normal).
---@field game_controller_interaction? defines.game_controller_interaction
---Whether this element will raise [on\_gui\_hover](https://lua-api.factorio.com/latest/events.html#on_gui_hover) and [on\_gui\_leave](https://lua-api.factorio.com/latest/events.html#on_gui_leave). Defaults to `false`.
---@field raise_hover_events? boolean
local LuaGuiElement_add_param_base={
}
end

---@alias LuaGuiElement.add_param (LuaGuiElement.add_param.button)|(LuaGuiElement.add_param.camera)|(LuaGuiElement.add_param.checkbox)|(LuaGuiElement.add_param.choose_elem_button)|(LuaGuiElement.add_param.drop_down)|(LuaGuiElement.add_param.flow)|(LuaGuiElement.add_param.frame)|(LuaGuiElement.add_param.line)|(LuaGuiElement.add_param.list_box)|(LuaGuiElement.add_param.minimap)|(LuaGuiElement.add_param.progressbar)|(LuaGuiElement.add_param.radiobutton)|(LuaGuiElement.add_param.scroll_pane)|(LuaGuiElement.add_param.slider)|(LuaGuiElement.add_param.sprite)|(LuaGuiElement.add_param.sprite_button)|(LuaGuiElement.add_param.switch)|(LuaGuiElement.add_param.tab)|(LuaGuiElement.add_param.table)|(LuaGuiElement.add_param.text_box)|(LuaGuiElement.add_param.textfield)|(LuaGuiElement.add_param.base)

do
---@class LuaGuiElement.add_param.button:LuaGuiElement.add_param.base
---Which mouse buttons the button responds to. Defaults to `"left-and-right"`.
---@field mouse_button_filter? MouseButtonFlags
---Whether the button will automatically toggle when clicked. Defaults to `false`.
---@field auto_toggle? boolean
---The initial toggled state of the button. Defaults to `false`.
---@field toggled? boolean
local LuaGuiElement_add_param_button={
}
end

do
---@class LuaGuiElement.add_param.camera:LuaGuiElement.add_param.base
---The position the camera centers on.
---@field position MapPosition
---The surface that the camera will render. Defaults to the player's current surface.
---@field surface_index? uint
---The initial camera zoom. Defaults to `0.75`.
---@field zoom? double
local LuaGuiElement_add_param_camera={
}
end

do
---@class LuaGuiElement.add_param.checkbox:LuaGuiElement.add_param.base
---The initial checked-state of the checkbox.
---@field state boolean
local LuaGuiElement_add_param_checkbox={
}
end

do
---@class LuaGuiElement.add_param.choose_elem_button:LuaGuiElement.add_param.base
---The type of the button.
---@field elem_type ElemType
---If type is `"item"` - the default value for the button.
---@field item? string
---If type is `"tile"` - the default value for the button.
---@field tile? string
---If type is `"entity"` - the default value for the button.
---@field entity? string
---If type is `"signal"` - the default value for the button.
---@field signal? SignalID
---If type is `"fluid"` - the default value for the button.
---@field fluid? string
---If type is `"recipe"` - the default value for the button.
---@field recipe? string
---If type is `"decorative"` - the default value for the button.
---@field decorative? string
---If type is `"item-group"` - the default value for the button.
---@field item-group? string
---If type is `"achievement"` - the default value for the button.
---@field achievement? string
---If type is `"equipment"` - the default value for the button.
---@field equipment? string
---If type is `"technology"` - the default value for the button.
---@field technology? string
---If type is `"item-with-quality"` - the default value for the button.
---@field item-with-quality? string
---If type is `"entity-with-quality"` - the default value for the button.
---@field entity-with-quality? string
---If type is `"recipe-with-quality"` - the default value for the button.
---@field recipe-with-quality? string
---If type is `"equipment-with-quality"` - the default value for the button.
---@field equipment-with-quality? string
---Filters describing what to show in the selection window. The applicable filter depends on the `elem_type`.
---@field elem_filters? PrototypeFilter
local LuaGuiElement_add_param_choose_elem_button={
}
end

do
---@class LuaGuiElement.add_param.drop_down:LuaGuiElement.add_param.base
---The initial items in the dropdown.
---@field items? (LocalisedString)[]
---The index of the initially selected item. Defaults to 0.
---@field selected_index? uint
local LuaGuiElement_add_param_drop_down={
}
end

do
---@class LuaGuiElement.add_param.flow:LuaGuiElement.add_param.base
---The initial direction of the flow's layout. Defaults to `"horizontal"`.
---@field direction? GuiDirection
local LuaGuiElement_add_param_flow={
}
end

do
---@class LuaGuiElement.add_param.frame:LuaGuiElement.add_param.base
---The initial direction of the frame's layout. Defaults to `"horizontal"`.
---@field direction? GuiDirection
local LuaGuiElement_add_param_frame={
}
end

do
---@class LuaGuiElement.add_param.line:LuaGuiElement.add_param.base
---The initial direction of the line. Defaults to `"horizontal"`.
---@field direction? GuiDirection
local LuaGuiElement_add_param_line={
}
end

do
---@class LuaGuiElement.add_param.list_box:LuaGuiElement.add_param.base
---The initial items in the listbox.
---@field items? (LocalisedString)[]
---The index of the initially selected item. Defaults to 0.
---@field selected_index? uint
local LuaGuiElement_add_param_list_box={
}
end

do
---@class LuaGuiElement.add_param.minimap:LuaGuiElement.add_param.base
---The position the minimap centers on. Defaults to the player's current position.
---@field position? MapPosition
---The surface the camera will render. Defaults to the player's current surface.
---@field surface_index? uint
---The player index the map should use. Defaults to the current player.
---@field chart_player_index? uint
---The force this minimap should use. Defaults to the player's current force.
---@field force? string
---The initial camera zoom. Defaults to `0.75`.
---@field zoom? double
local LuaGuiElement_add_param_minimap={
}
end

do
---@class LuaGuiElement.add_param.progressbar:LuaGuiElement.add_param.base
---The initial value of the progressbar, in the range `[0, 1]`. Defaults to `0`.
---@field value? double
local LuaGuiElement_add_param_progressbar={
}
end

do
---@class LuaGuiElement.add_param.radiobutton:LuaGuiElement.add_param.base
---The initial checked-state of the radiobutton.
---@field state boolean
local LuaGuiElement_add_param_radiobutton={
}
end

do
---@class LuaGuiElement.add_param.scroll_pane:LuaGuiElement.add_param.base
---Policy of the horizontal scroll bar. Defaults to `"auto"`.
---@field horizontal_scroll_policy? ScrollPolicy
---Policy of the vertical scroll bar. Defaults to `"auto"`.
---@field vertical_scroll_policy? ScrollPolicy
local LuaGuiElement_add_param_scroll_pane={
}
end

do
---@class LuaGuiElement.add_param.slider:LuaGuiElement.add_param.base
---The minimum value for the slider. Defaults to `0`.
---@field minimum_value? double
---The maximum value for the slider. Defaults to `30`.
---@field maximum_value? double
---The initial value for the slider. Defaults to `minimum_value`.
---@field value? double
---The minimum value the slider can move. Defaults to `1`.
---@field value_step? double
---Defaults to `true`.
---@field discrete_values? boolean
local LuaGuiElement_add_param_slider={
}
end

do
---@class LuaGuiElement.add_param.sprite:LuaGuiElement.add_param.base
---Path to the image to display.
---@field sprite? SpritePath
---Whether the widget should resize according to the sprite in it. Defaults to `true`.
---@field resize_to_sprite? boolean
local LuaGuiElement_add_param_sprite={
}
end

do
---@class LuaGuiElement.add_param.sprite_button:LuaGuiElement.add_param.base
---Path to the image to display on the button.
---@field sprite? SpritePath
---Path to the image to display on the button when it is hovered.
---@field hovered_sprite? SpritePath
---Path to the image to display on the button when it is clicked.
---@field clicked_sprite? SpritePath
---The number shown on the button.
---@field number? double
---Formats small numbers as percentages. Defaults to `false`.
---@field show_percent_for_small_numbers? boolean
---The mouse buttons that the button responds to. Defaults to `"left-and-right"`.
---@field mouse_button_filter? MouseButtonFlags
---Whether the button will automatically toggle when clicked. Defaults to `false`.
---@field auto_toggle? boolean
---The initial toggled state of the button. Defaults to `false`.
---@field toggled? boolean
local LuaGuiElement_add_param_sprite_button={
}
end

do
---@class LuaGuiElement.add_param.switch:LuaGuiElement.add_param.base
---If set to "none", `allow_none_state` must be `true`. Defaults to `"left"`.
---@field switch_state? SwitchState
---Whether the switch can be set to a middle state. Defaults to `false`.
---@field allow_none_state? boolean
---@field left_label_caption? LocalisedString
---@field left_label_tooltip? LocalisedString
---@field right_label_caption? LocalisedString
---@field right_label_tooltip? LocalisedString
local LuaGuiElement_add_param_switch={
}
end

do
---@class LuaGuiElement.add_param.tab:LuaGuiElement.add_param.base
---The text to display after the normal tab text (designed to work with numbers).
---@field badge_text? LocalisedString
local LuaGuiElement_add_param_tab={
}
end

do
---@class LuaGuiElement.add_param.table:LuaGuiElement.add_param.base
---Number of columns. This can't be changed after the table is created.
---@field column_count uint
---Whether the table should draw vertical grid lines. Defaults to `false`.
---@field draw_vertical_lines? boolean
---Whether the table should draw horizontal grid lines. Defaults to `false`.
---@field draw_horizontal_lines? boolean
---Whether the table should draw a single horizontal grid line after the headers. Defaults to `false`.
---@field draw_horizontal_line_after_headers? boolean
---Whether the content of the table should be vertically centered. Defaults to `true`.
---@field vertical_centering? boolean
local LuaGuiElement_add_param_table={
}
end

do
---@class LuaGuiElement.add_param.text_box:LuaGuiElement.add_param.base
---The initial text contained in the text-box.
---@field text? string
---Whether to add the rich text icon selector to the text box. This attribute can't be changed after creating the widget. Defaults to `false`.
---@field icon_selector? boolean
local LuaGuiElement_add_param_text_box={
}
end

do
---@class LuaGuiElement.add_param.textfield:LuaGuiElement.add_param.base
---The initial text contained in the textfield.
---@field text? string
---Defaults to `false`.
---@field numeric? boolean
---Defaults to `false`.
---@field allow_decimal? boolean
---Defaults to `false`.
---@field allow_negative? boolean
---Defaults to `false`.
---@field is_password? boolean
---Defaults to `false`.
---@field lose_focus_on_confirm? boolean
---Whether to add the rich text icon selector to the text field. This attribute can't be changed after creating the widget. Defaults to `false`.
---@field icon_selector? boolean
local LuaGuiElement_add_param_textfield={
}
end

do
---An element of a custom GUI. This type is used to represent [any kind](https://lua-api.factorio.com/latest/concepts.html#GuiElementType) of a GUI element - labels, buttons and frames are all instances of this type. Just like [LuaEntity](https://lua-api.factorio.com/latest/classes/LuaEntity.html), different kinds of elements support different attributes; attempting to access an attribute on an element that doesn't support it (for instance, trying to access the `column_count` of a `textfield`) will result in a runtime error.
---
---For information on all supported GUI elements, see [GuiElementType](https://lua-api.factorio.com/latest/concepts.html#GuiElementType).
---
---Each GUI element allows access to its children by having them as attributes. Thus, one can use the `parent.child` syntax to refer to children. Lua also supports the `parent["child"]` syntax to refer to the same element. This can be used in cases where the child has a name that isn't a valid Lua identifier.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html)
---
---### Example
---
---```
----- This will add a label called "greeting" to the top flow.
----- Immediately after, it will change its text to illustrate accessing child elements.
---game.player.gui.top.add{type="label", name="greeting", caption="Hi"}
---game.player.gui.top.greeting.caption = "Hello there!"
---game.player.gui.top["greeting"].caption = "Actually, never mind, I don't like your face"
---```
---
---### Example
---
---```
----- This will add a tabbed-pane and 2 tabs with contents.
---local tabbed_pane = game.player.gui.top.add{type="tabbed-pane"}
---local tab1 = tabbed_pane.add{type="tab", caption="Tab 1"}
---local tab2 = tabbed_pane.add{type="tab", caption="Tab 2"}
---local label1 = tabbed_pane.add{type="label", caption="Label 1"}
---local label2 = tabbed_pane.add{type="label", caption="Label 2"}
---tabbed_pane.add_tab(tab1, label1)
---tabbed_pane.add_tab(tab2, label2)
---```
---@class LuaGuiElement:LuaObject, LuaGuiElement_funcs
---Whether this textfield (when in numeric mode) allows decimal numbers.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#allow_decimal)
---
---*Can only be used if this is textfield*
---@field allow_decimal boolean
---Whether this textfield (when in numeric mode) allows negative numbers.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#allow_negative)
---
---*Can only be used if this is textfield*
---@field allow_negative boolean
---Whether the `"none"` state is allowed for this switch.
---
---This can't be set to false if the current switch\_state is 'none'.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#allow_none_state)
---
---*Can only be used if this is switch*
---@field allow_none_state boolean
---The anchor for this relative widget, if any. Setting `nil` clears the anchor.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#anchor)
---@field anchor? GuiAnchor
---Whether this frame auto-centers on window resize when stored in [LuaGui::screen](https://lua-api.factorio.com/latest/classes/LuaGui.html#screen).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#auto_center)
---
---*Can only be used if this is frame*
---@field auto_center boolean
---Whether this button will automatically toggle when clicked.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#auto_toggle)
---
---*Can only be used if this is button or sprite-button*
---@field auto_toggle boolean
---The text to display after the normal tab text (designed to work with numbers)
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#badge_text)
---
---*Can only be used if this is tab*
---@field badge_text LocalisedString
---The text displayed on this element. For frames, this is the "heading". For other elements, like buttons or labels, this is the content.
---
---Whilst this attribute may be used on all elements without producing an error, it doesn't make sense for tables and flows as they won't display it.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#caption)
---@field caption LocalisedString
---The child-elements of this GUI element.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#children)
---@field children (LuaGuiElement)[]
---Names of all the children of this element. These are the identifiers that can be used to access the child as an attribute of this element.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#children_names)
---@field children_names (string)[]
---The sprite to display on this sprite-button when it is clicked.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#clicked_sprite)
---
---*Can only be used if this is sprite-button*
---@field clicked_sprite SpritePath
---The number of columns in this table.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#column_count)
---
---*Can only be used if this is table*
---@field column_count uint
---Direction of this element's layout.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#direction)
---
---*Can only be used if this is frame, flow or line*
---@field direction GuiDirection
---The `frame` that is being moved when dragging this GUI element, if any. This element needs to be a child of the `drag_target` at some level.
---
---Only top-level elements in [LuaGui::screen](https://lua-api.factorio.com/latest/classes/LuaGui.html#screen) can be `drag_target`s.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#drag_target)
---
---### Example
---
---```
----- This creates a frame that contains a dragging handle which can move the frame.
---local frame = player.gui.screen.add{type="frame", direction="vertical"}
---local dragger = frame.add{type="empty-widget", style="draggable_space"}
---dragger.style.size = {128, 24}
---dragger.drag_target = frame
---```
---
---*Can only be used if this is flow, frame, label, table or empty-widget*
---@field drag_target? LuaGuiElement
---Whether this table should draw a horizontal grid line below the first table row.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#draw_horizontal_line_after_headers)
---
---*Can only be used if this is table*
---@field draw_horizontal_line_after_headers boolean
---Whether this table should draw horizontal grid lines.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#draw_horizontal_lines)
---
---*Can only be used if this is table*
---@field draw_horizontal_lines boolean
---Whether this table should draw vertical grid lines.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#draw_vertical_lines)
---
---*Can only be used if this is table*
---@field draw_vertical_lines boolean
---The elem filters of this choose-elem-button, if any. The compatible type of filter is determined by `elem_type`.
---
---Writing to this field does not change or clear the currently selected element.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#elem_filters)
---
---### Example
---
---```
----- This will configure a choose-elem-button of type "entity" to only show items of type "furnace".
---button.elem_filters = {{filter = "type", type = "furnace"}}
---```
---
---### Example
---
---```
----- Then, there are some types of filters that work on a specific kind of attribute. The following will configure a
-----   choose-elem-button of type "entity" to only show entities that have their "hidden" flags set.
---button.elem_filters = {{filter = "hidden"}}
---```
---
---### Example
---
---```
----- Lastly, these filters can be combined at will, taking care to specify how they should be combined (either "and" or "or").
-----   The following will filter for any entities that are "furnaces" and that are not "hidden".
---button.elem_filters = {{filter = "type", type = "furnace"}, {filter = "hidden", invert = true, mode = "and"}}
---```
---
---*Can only be used if this is choose-elem-button*
---@field elem_filters? PrototypeFilter
---The element tooltip to display when hovering over this element, or `nil`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#elem_tooltip)
---@field elem_tooltip? ElemID
---The elem type of this choose-elem-button.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#elem_type)
---
---*Can only be used if this is choose-elem-button*
---@field elem_type ElemType
---The elem value of this choose-elem-button, if any.
---
---The `"signal"` type operates with [SignalID](https://lua-api.factorio.com/latest/concepts.html#SignalID).
---
---The `"with-quality"` types operate with `"name"` and optional `"quality"`
---
---The remaining types use strings.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#elem_value)
---
---*Can only be used if this is choose-elem-button*
---@field elem_value? (string)|(SignalID)|(table)
---Whether this GUI element is enabled. Disabled GUI elements don't trigger events when clicked.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#enabled)
---@field enabled boolean
---The entity associated with this entity-preview, camera, minimap, if any.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#entity)
---
---*Can only be used if this is entity-preview, camera or minimap*
---@field entity? LuaEntity
---The force this minimap is using, if any.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#force)
---
---*Can only be used if this is minimap*
---@field force? string
---How this element should interact with game controllers.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#game_controller_interaction)
---@field game_controller_interaction defines.game_controller_interaction
---The GUI this element is a child of.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#gui)
---@field gui LuaGui
---Policy of the horizontal scroll bar.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#horizontal_scroll_policy)
---
---*Can only be used if this is scroll-pane*
---@field horizontal_scroll_policy ScrollPolicy
---The sprite to display on this sprite-button when it is hovered.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#hovered_sprite)
---
---*Can only be used if this is sprite-button*
---@field hovered_sprite SpritePath
---Whether this GUI element is ignored by interaction. This makes clicks on this element 'go through' to the GUI element or even the game surface below it.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#ignored_by_interaction)
---@field ignored_by_interaction boolean
---The index of this GUI element (unique amongst the GUI elements of a LuaPlayer).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#index)
---@field index uint
---Whether this textfield displays as a password field, which renders all characters as `*`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#is_password)
---
---*Can only be used if this is textfield*
---@field is_password boolean
---The items in this dropdown or listbox.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#items)
---
---*Can only be used if this is drop-down or list-box*
---@field items (LocalisedString)[]
---The text shown for the left switch label.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#left_label_caption)
---
---*Can only be used if this is switch*
---@field left_label_caption LocalisedString
---The tooltip shown on the left switch label.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#left_label_tooltip)
---
---*Can only be used if this is switch*
---@field left_label_tooltip LocalisedString
---The location of this widget when stored in [LuaGui::screen](https://lua-api.factorio.com/latest/classes/LuaGui.html#screen). `nil` if not set or not in [LuaGui::screen](https://lua-api.factorio.com/latest/classes/LuaGui.html#screen).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#location)
---@field location? GuiLocation
---Whether this choose-elem-button can be changed by the player.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#locked)
---
---*Can only be used if this is choose-elem-button*
---@field locked boolean
---Whether this textfield loses focus after [defines.events.on\_gui\_confirmed](https://lua-api.factorio.com/latest/defines.html#defines.events.on_gui_confirmed) is fired.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#lose_focus_on_confirm)
---
---*Can only be used if this is textfield*
---@field lose_focus_on_confirm boolean
---The player index this minimap is using.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#minimap_player_index)
---
---*Can only be used if this is minimap*
---@field minimap_player_index uint
---The mouse button filters for this button or sprite-button.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#mouse_button_filter)
---
---*Can only be used if this is button or sprite-button*
---@field mouse_button_filter MouseButtonFlags
---The name of this element. `""` if no name was set.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#name)
---
---### Example
---
---```
---game.player.gui.top.greeting.name == "greeting"
---```
---@field name string
---The number to be shown in the bottom right corner of this sprite-button, or `nil` to show nothing.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#number)
---
---*Can only be used if this is sprite-button*
---@field number? double
---Whether this textfield is limited to only numeric characters.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#numeric)
---
---*Can only be used if this is textfield*
---@field numeric boolean
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#object_name)
---@field object_name string
---The direct parent of this element. `nil` if this is a top-level element.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#parent)
---@field parent? LuaGuiElement
---Index into [LuaGameScript::players](https://lua-api.factorio.com/latest/classes/LuaGameScript.html#players) specifying the player who owns this element.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#player_index)
---@field player_index uint
---The position this camera or minimap is focused on, if any.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#position)
---
---*Can only be used if this is camera or minimap*
---@field position MapPosition
---Whether this element will raise [on\_gui\_hover](https://lua-api.factorio.com/latest/events.html#on_gui_hover) and [on\_gui\_leave](https://lua-api.factorio.com/latest/events.html#on_gui_leave).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#raise_hover_events)
---@field raise_hover_events boolean
---Whether this text-box is read-only. Defaults to `false`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#read_only)
---
---*Can only be used if this is text-box*
---@field read_only boolean
---Whether the sprite widget should resize according to the sprite in it. Defaults to `true`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#resize_to_sprite)
---
---*Can only be used if this is sprite*
---@field resize_to_sprite boolean
---The text shown for the right switch label.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#right_label_caption)
---
---*Can only be used if this is switch*
---@field right_label_caption LocalisedString
---The tooltip shown on the right switch label.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#right_label_tooltip)
---
---*Can only be used if this is switch*
---@field right_label_tooltip LocalisedString
---Whether the contents of this text-box are selectable. Defaults to `true`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#selectable)
---
---*Can only be used if this is text-box*
---@field selectable boolean
---The selected index for this dropdown or listbox. Returns `0` if none is selected.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#selected_index)
---
---*Can only be used if this is drop-down or list-box*
---@field selected_index uint
---The selected tab index for this tabbed pane, if any.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#selected_tab_index)
---
---*Can only be used if this is tabbed-pane*
---@field selected_tab_index? uint
---Related to the number to be shown in the bottom right corner of this sprite-button. When set to `true`, numbers that are non-zero and smaller than one are shown as a percentage rather than the value. For example, `0.5` will be shown as `50%` instead.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#show_percent_for_small_numbers)
---
---*Can only be used if this is sprite-button*
---@field show_percent_for_small_numbers boolean
---The value of this slider element.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#slider_value)
---
---*Can only be used if this is slider*
---@field slider_value double
---The sprite to display on this sprite-button or sprite in the default state.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#sprite)
---
---*Can only be used if this is sprite-button or sprite*
---@field sprite SpritePath
---Is this checkbox or radiobutton checked?
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#state)
---
---*Can only be used if this is checkbox or radiobutton*
---@field state boolean
---The style of this element. When read, this evaluates to a [LuaStyle](https://lua-api.factorio.com/latest/classes/LuaStyle.html). For writing, it only accepts a string that specifies the textual identifier (prototype name) of the desired style.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#style)
---@field style (LuaStyle)|(string)
---The surface index this camera or minimap is using.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#surface_index)
---
---*Can only be used if this is camera or minimap*
---@field surface_index uint
---The switch state for this switch.
---
---If [LuaGuiElement::allow\_none\_state](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#allow_none_state) is false this can't be set to `"none"`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#switch_state)
---
---*Can only be used if this is switch*
---@field switch_state SwitchState
---The tabs and contents being shown in this tabbed-pane.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#tabs)
---
---*Can only be used if this is tabbed-pane*
---@field tabs (TabAndContent)[]
---The tags associated with this LuaGuiElement.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#tags)
---@field tags Tags
---The text contained in this textfield or text-box.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#text)
---
---*Can only be used if this is textfield or text-box*
---@field text string
---Whether this button is currently toggled. When a button is toggled, it will use the `selected_graphical_set` and `selected_font_color` defined in its style.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#toggled)
---
---*Can only be used if this is button or sprite-button*
---@field toggled boolean
---The text to display when hovering over this element. Writing `""` or `nil` will disable the tooltip.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#tooltip)
---@field tooltip LocalisedString
---The type of this GUI element.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#type)
---@field type GuiElementType
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#valid)
---@field valid boolean
---How much this progress bar is filled. It is a value in the range `[0, 1]`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#value)
---
---*Can only be used if this is progressbar*
---@field value double
---Whether the content of this table should be vertically centered. Overrides [LuaStyle::column\_alignments](https://lua-api.factorio.com/latest/classes/LuaStyle.html#column_alignments). Defaults to `true`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#vertical_centering)
---
---*Can only be used if this is table*
---@field vertical_centering boolean
---Policy of the vertical scroll bar.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#vertical_scroll_policy)
---
---*Can only be used if this is scroll-pane*
---@field vertical_scroll_policy ScrollPolicy
---Sets whether this GUI element is visible or completely hidden, taking no space in the layout.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#visible)
---@field visible boolean
---Whether this text-box will word-wrap automatically. Defaults to `false`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#word_wrap)
---
---*Can only be used if this is text-box*
---@field word_wrap boolean
---The zoom this camera or minimap is using. This value must be positive.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#zoom)
---
---*Can only be used if this is camera or minimap*
---@field zoom double
---The indexing operator. Gets children by name.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaGuiElement.html#index_operator)
---@field [(string)|(uint)] LuaGuiElement
local LuaGuiElement={
}
end

