---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaHelpers
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Provides various helper and utility functions. It is accessible through the global object named `helpers`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaHelpers.html)
---@class LuaHelpers:LuaObject
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaHelpers.html#object_name)
---@field object_name string
helpers={
---Goes over all items, entities, tiles, recipes, technologies among other things and logs if the locale is incorrect.
---
---Also prints true/false if called from the console.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaHelpers.html#check_prototype_translations)
check_prototype_translations = function() end;
---Creates a [LuaProfiler](https://lua-api.factorio.com/latest/classes/LuaProfiler.html), which is used for measuring script performance.
---
---LuaProfiler cannot be serialized.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaHelpers.html#create_profiler)
---@param stopped? boolean Create the timer stopped
---@return LuaProfiler 
create_profiler = function(stopped) end;
---Base64 decodes and inflates the given string.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaHelpers.html#decode_string)
---@param string string The string to decode.
---@return string?  #The decoded string or `nil` if the decode failed.
decode_string = function(string) end;
---Converts the given direction into the string version of the direction.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaHelpers.html#direction_to_string)
---@param direction defines.direction 
---@return string 
direction_to_string = function(direction) end;
---Deflates and base64 encodes the given string.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaHelpers.html#encode_string)
---@param string string The string to encode.
---@return string?  #The encoded string or `nil` if the encode failed.
encode_string = function(string) end;
---Evaluate an expression, substituting variables as provided.
---
---### Example
---
---```
----- Calculate the number of research units required to unlock mining productivity level 10
---local formula = game.forces["player"].technologies["mining-productivity-4"].research_unit_count_formula
---local units = helpers.evaluate_expression(formula, { L = 10, l = 10 })
---```
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaHelpers.html#evaluate_expression)
---@param expression MathExpression The expression to evaluate.
---@param variables? {[string]:double} Variables to be substituted.
---@return double 
evaluate_expression = function(expression, variables) end;
---Checks if the given SoundPath is valid.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaHelpers.html#is_valid_sound_path)
---@param sound_path SoundPath Path to the sound.
---@return boolean 
is_valid_sound_path = function(sound_path) end;
---Checks if the given SpritePath is valid and contains a loaded sprite. The existence of the image is not checked for paths of type `file`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaHelpers.html#is_valid_sprite_path)
---@param sprite_path SpritePath Path to the image.
---@return boolean 
is_valid_sprite_path = function(sprite_path) end;
---Convert a JSON string to a table.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaHelpers.html#json_to_table)
---@param json string The string to convert.
---@return AnyBasic?  #The returned object, or `nil` if the JSON string was invalid.
json_to_table = function(json) end;
---Convert a map exchange string to map gen settings and map settings.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaHelpers.html#parse_map_exchange_string)
---@param map_exchange_string string 
---@return MapExchangeStringData 
parse_map_exchange_string = function(map_exchange_string) end;
---Remove a file or directory in the `script-output` folder, located in the game's [user data directory](https://wiki.factorio.com/User_data_directory). Can be used to remove files created by [LuaHelpers::write\_file](https://lua-api.factorio.com/latest/classes/LuaHelpers.html#write_file).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaHelpers.html#remove_path)
---@param path string The path to the file or directory to remove, relative to `script-output`.
remove_path = function(path) end;
---Convert a table to a JSON string
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaHelpers.html#table_to_json)
---@param data table 
---@return string 
table_to_json = function(data) end;
---Write a file to the `script-output` folder, located in the game's [user data directory](https://wiki.factorio.com/User_data_directory). The name and file extension of the file can be specified via the `filename` parameter.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaHelpers.html#write_file)
---@param filename string The name of the file. Providing a directory path (ex. `"save/here/example.txt"`) will create the necessary folder structure in `script-output`.
---@param data LocalisedString The content to write to the file.
---@param append? boolean If `true`, `data` will be appended to the end of the file. Defaults to `false`, which will overwrite any pre-existing file with the new `data`.
---@param for_player? uint If given, the file will only be written for this `player_index`. Providing `0` will only write to the server's output if present.
write_file = function(filename, data, append, for_player) end;
}
end

