---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaInserterControlBehavior
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Control behavior for inserters.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaInserterControlBehavior.html)
---@class LuaInserterControlBehavior:LuaGenericOnOffControlBehavior
---The hand read mode for the inserter.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaInserterControlBehavior.html#circuit_hand_read_mode)
---@field circuit_hand_read_mode defines.control_behavior.inserter.hand_read_mode
---`true` if the contents of the inserter hand should be sent to the circuit network
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaInserterControlBehavior.html#circuit_read_hand_contents)
---@field circuit_read_hand_contents boolean
---`true` if filters are set from circuit network
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaInserterControlBehavior.html#circuit_set_filters)
---@field circuit_set_filters boolean
---If the stack size of the inserter is set through the circuit network or not.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaInserterControlBehavior.html#circuit_set_stack_size)
---@field circuit_set_stack_size boolean
---The signal used to set the stack size of the inserter.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaInserterControlBehavior.html#circuit_stack_control_signal)
---@field circuit_stack_control_signal? SignalID
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaInserterControlBehavior.html#object_name)
---@field object_name string
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaInserterControlBehavior.html#valid)
---@field valid boolean
local LuaInserterControlBehavior={
}
end

