---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaItemCommon
-- This file is automatically generated. Edits will be overwritten without warning.

do
---@class LuaItemCommon.build_blueprint_param
---Surface to build on
---@field surface SurfaceIdentification
---Force to use for the building
---@field force ForceID
---The position to build at
---@field position MapPosition
---The direction to use when building
---@field direction? defines.direction
---If `normal`, blueprint will not be built if any one thing can't be built. If `forced`, anything that can be built is built and obstructing nature entities will be deconstructed. If `superforced`, all obstructions will be deconstructed and the blueprint will be built.
---@field build_mode? defines.build_mode
---If chunks covered by fog-of-war are skipped.
---@field skip_fog_of_war? boolean
---The player to use if any. If provided [defines.events.on\_built\_entity](https://lua-api.factorio.com/latest/defines.html#defines.events.on_built_entity) will also be fired on successful entity creation.
---@field by_player? PlayerIdentification
---If true; [defines.events.script\_raised\_built](https://lua-api.factorio.com/latest/defines.html#defines.events.script_raised_built) will be fired on successful entity creation. Note: this is ignored if by\_player is provided.
---@field raise_built? boolean
local LuaItemCommon_build_blueprint_param={
}
end

do
---@class LuaItemCommon.cancel_deconstruct_area_param
---Surface to cancel deconstruct on
---@field surface SurfaceIdentification
---Force to use for canceling deconstruction
---@field force ForceID
---The area to deconstruct
---@field area BoundingBox
---If chunks covered by fog-of-war are skipped. Defaults to `false`.
---@field skip_fog_of_war? boolean
---The player to use if any.
---@field by_player? PlayerIdentification
---If the cancel deconstruction is super-forced. Defaults to `false`.
---@field super_forced? boolean
local LuaItemCommon_cancel_deconstruct_area_param={
}
end

do
---@class LuaItemCommon.create_blueprint_param
---Surface to create from
---@field surface SurfaceIdentification
---Force to use for the creation
---@field force ForceID
---The bounding box
---@field area BoundingBox
---When true, blueprintable tiles are always included in the blueprint. When false they're only included if no entities exist in the setup area.
---@field always_include_tiles? boolean
---When true, entities are included in the blueprint. Defaults to true.
---@field include_entities? boolean
---When true, modules are included in the blueprint. Defaults to true.
---@field include_modules? boolean
---When true, station names are included in the blueprint. Defaults to false.
---@field include_station_names? boolean
---When true, trains are included in the blueprint. Defaults to false.
---@field include_trains? boolean
---When true, train fuel is included in the blueprint, Defaults to true.
---@field include_fuel? boolean
local LuaItemCommon_create_blueprint_param={
}
end

do
---@class LuaItemCommon.deconstruct_area_param
---Surface to deconstruct on
---@field surface SurfaceIdentification
---Force to use for the deconstruction
---@field force ForceID
---The area to deconstruct
---@field area BoundingBox
---If chunks covered by fog-of-war are skipped. Defaults to `false`.
---@field skip_fog_of_war? boolean
---The player to use if any.
---@field by_player? PlayerIdentification
---If the deconstruction is super-forced. Defaults to `false`.
---@field super_forced? boolean
local LuaItemCommon_deconstruct_area_param={
}
end

do
---Common methods related to usage of item with data. It is useful when LuaItemStack contains item with data or in general with LuaItem as it can only point at an item with data.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html)
---@class LuaItemCommon:LuaObject
---The active blueprint index for this blueprint book. `nil` if this blueprint book is empty.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#active_index)
---
---*Can only be used if this is BlueprintBookItem*
---@field active_index? uint
---Whether the label for this item can be manually changed. When false the label can only be changed through the API.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#allow_manual_label_change)
---
---*Can only be used if this is ItemWithLabel*
---@field allow_manual_label_change boolean
---Number of bullets left in the magazine.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#ammo)
---
---*Can only be used if this is AmmoItem*
---@field ammo uint
---If absolute snapping is enabled on this blueprint item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#blueprint_absolute_snapping)
---
---*Can only be used if this is BlueprintItem*
---@field blueprint_absolute_snapping boolean
---The offset from the absolute grid. `nil` if absolute snapping is not enabled.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#blueprint_position_relative_to_grid)
---
---*Can only be used if this is BlueprintItem*
---@field blueprint_position_relative_to_grid? TilePosition
---The snapping grid size in this blueprint item. `nil` if snapping is not enabled.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#blueprint_snap_to_grid)
---
---*Can only be used if this is BlueprintItem*
---@field blueprint_snap_to_grid? TilePosition
---List of raw materials required to build this blueprint.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#cost_to_build)
---
---*Can only be used if this is BlueprintItem*
---@field cost_to_build (ItemCountWithQuality)[]
---The custom description this item-with-tags. This is shown over the normal item description if this is set to a non-empty value.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#custom_description)
---
---*Can only be used if this is ItemWithTags*
---@field custom_description LocalisedString
---The default icons for a blueprint item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#default_icons)
---
---*Can only be used if this is BlueprintItem*
---@field default_icons (BlueprintSignalIcon)[]
---Durability of the contained item. Automatically capped at the item's maximum durability.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#durability)
---
---*Can only be used if this is Tool*
---@field durability double
---If this is an item with entity data, get the stored entity color.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#entity_color)
---
---*Can only be used if this is ItemWithEntityData*
---@field entity_color? Color
---The number of entity filters this deconstruction item supports.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#entity_filter_count)
---
---*Can only be used if this is DeconstructionItem*
---@field entity_filter_count uint
---The blacklist/whitelist entity filter mode for this deconstruction item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#entity_filter_mode)
---
---*Can only be used if this is DeconstructionItem*
---@field entity_filter_mode defines.deconstruction_item.entity_filter_mode
---The entity filters for this deconstruction item. The attribute is a sparse array with the keys representing the index of the filter. All strings in this array must be entity prototype names that don't have the `"not-deconstructable"` flag set and are either a `cliff` or marked as `minable`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#entity_filters)
---
---*Can only be used if this is DeconstructionItem*
---@field entity_filters (string)[]
---If this is an item with entity data, get the stored entity label.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#entity_label)
---
---*Can only be used if this is ItemWithEntityData*
---@field entity_label? string
---The equipment grid of this item, if any.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#grid)
---@field grid? LuaEquipmentGrid
---If this is an ammo item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#is_ammo)
---@field is_ammo boolean
---If this is an armor item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#is_armor)
---@field is_armor boolean
---If this is a blueprint item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#is_blueprint)
---@field is_blueprint boolean
---If this is a blueprint book item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#is_blueprint_book)
---@field is_blueprint_book boolean
---If this is a deconstruction tool item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#is_deconstruction_item)
---@field is_deconstruction_item boolean
---If this is an item with entity data item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#is_item_with_entity_data)
---@field is_item_with_entity_data boolean
---If this is an item with inventory item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#is_item_with_inventory)
---@field is_item_with_inventory boolean
---If this is an item with label item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#is_item_with_label)
---@field is_item_with_label boolean
---If this is an item with tags item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#is_item_with_tags)
---@field is_item_with_tags boolean
---If this is a repair tool item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#is_repair_tool)
---@field is_repair_tool boolean
---If this is a selection tool item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#is_selection_tool)
---@field is_selection_tool boolean
---If this is a tool item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#is_tool)
---@field is_tool boolean
---If this is a upgrade item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#is_upgrade_item)
---@field is_upgrade_item boolean
---The unique identifier for this item, if any. Note that this ID stays the same no matter where the item is moved to.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#item_number)
---@field item_number? uint
---The current label for this item, if any.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#label)
---
---*Can only be used if this is ItemWithLabel*
---@field label? string
---The current label color for this item, if any.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#label_color)
---
---*Can only be used if this is ItemWithLabel*
---@field label_color? Color
---The current count of mappers in the upgrade item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#mapper_count)
---
---*Can only be used if this is UpgradeItem*
---@field mapper_count uint
---The location of this item if it can be found.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#owner_location)
---@field owner_location ItemLocationData
---Icons of this blueprint item, blueprint book, deconstruction item or upgrade planner. An item that doesn't have icons returns `nil` on read and throws error on write.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#preview_icons)
---@field preview_icons? (BlueprintSignalIcon)[]
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#tags)
---
---*Can only be used if this is ItemWithTags*
---@field tags Tags
---The number of tile filters this deconstruction item supports.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#tile_filter_count)
---
---*Can only be used if this is DeconstructionItem*
---@field tile_filter_count uint
---The blacklist/whitelist tile filter mode for this deconstruction item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#tile_filter_mode)
---
---*Can only be used if this is DeconstructionItem*
---@field tile_filter_mode defines.deconstruction_item.tile_filter_mode
---The tile filters for this deconstruction item. The attribute is a sparse array with the keys representing the index of the filter. Reading filters always returns an array of strings which are the tile prototype names.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#tile_filters)
---
---*Can only be used if this is DeconstructionItem*
---@field tile_filters (TileID)[]
---The tile selection mode for this deconstruction item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#tile_selection_mode)
---
---*Can only be used if this is DeconstructionItem*
---@field tile_selection_mode defines.deconstruction_item.tile_selection_mode
---If this deconstruction item is set to allow trees and rocks only.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#trees_and_rocks_only)
---
---*Can only be used if this is DeconstructionItem*
---@field trees_and_rocks_only boolean
local LuaItemCommon={
---Build this blueprint at the given location.
---
---Built entities can be come invalid between the building of the blueprint and the function returning if by\_player or raise\_built is used and one of those events invalidates the entity.
---
---*Can only be used if this is BlueprintItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#build_blueprint)
---@param param LuaItemCommon.build_blueprint_param 
---@return (LuaEntity)[]  #Array of created ghosts
build_blueprint = function(param) end;
---Cancel deconstruct the given area with this deconstruction item.
---
---*Can only be used if this is DeconstructionItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#cancel_deconstruct_area)
---@param param LuaItemCommon.cancel_deconstruct_area_param 
cancel_deconstruct_area = function(param) end;
---Clears this blueprint item.
---
---*Can only be used if this is BlueprintItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#clear_blueprint)
clear_blueprint = function() end;
---Clears all settings/filters on this deconstruction item resetting it to default values.
---
---*Can only be used if this is DeconstructionItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#clear_deconstruction_item)
clear_deconstruction_item = function() end;
---Clears all settings/filters on this upgrade item resetting it to default values.
---
---*Can only be used if this is UpgradeItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#clear_upgrade_item)
clear_upgrade_item = function() end;
---Sets up this blueprint using the found blueprintable entities/tiles on the surface.
---
---*Can only be used if this is BlueprintItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#create_blueprint)
---@param param LuaItemCommon.create_blueprint_param 
---@return {[uint]:LuaEntity}  #The blueprint entity index to source entity mapping.
create_blueprint = function(param) end;
---Deconstruct the given area with this deconstruction item.
---
---*Can only be used if this is DeconstructionItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#deconstruct_area)
---@param param LuaItemCommon.deconstruct_area_param 
deconstruct_area = function(param) end;
---The entities in this blueprint.
---
---*Can only be used if this is BlueprintItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#get_blueprint_entities)
---@return (BlueprintEntity)[]? 
get_blueprint_entities = function() end;
---Gets the number of entities in this blueprint item.
---
---*Can only be used if this is BlueprintItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#get_blueprint_entity_count)
---@return uint 
get_blueprint_entity_count = function() end;
---Gets the given tag on the given blueprint entity index in this blueprint item.
---
---*Can only be used if this is BlueprintItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#get_blueprint_entity_tag)
---@param index uint The entity index.
---@param tag string The tag to get.
---@return AnyBasic? 
get_blueprint_entity_tag = function(index, tag) end;
---Gets the tags for the given blueprint entity index in this blueprint item.
---
---*Can only be used if this is BlueprintItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#get_blueprint_entity_tags)
---@param index uint 
---@return Tags 
get_blueprint_entity_tags = function(index) end;
---A list of the tiles in this blueprint.
---
---*Can only be used if this is BlueprintItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#get_blueprint_tiles)
---@return (Tile)[]? 
get_blueprint_tiles = function() end;
---Gets the entity filter at the given index for this deconstruction item.
---
---*Can only be used if this is DeconstructionItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#get_entity_filter)
---@param index uint 
---@return string? 
get_entity_filter = function(index) end;
---Access the inner inventory of an item.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#get_inventory)
---@param inventory defines.inventory Index of the inventory to access, which can only be [defines.inventory.item\_main](https://lua-api.factorio.com/latest/defines.html#defines.inventory.item_main).
---@return LuaInventory?  #`nil` if there is no inventory with the given index.
get_inventory = function(inventory) end;
---Gets the filter at the given index for this upgrade item.
---
---In contrast to [LuaItemCommon::set\_mapper](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#set_mapper), indices past the upgrade item's current size are considered to be out of bounds.
---
---*Can only be used if this is UpgradeItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#get_mapper)
---@param index uint The index of the mapper to read.
---@param type ("from")|("to") 
---@return (UpgradeMapperSource)|(UpgradeMapperDestination) 
get_mapper = function(index, type) end;
---Gets the tag with the given name or returns `nil` if it doesn't exist.
---
---*Can only be used if this is ItemWithTags*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#get_tag)
---@param tag_name string 
---@return AnyBasic? 
get_tag = function(tag_name) end;
---Gets the tile filter at the given index for this deconstruction item.
---
---*Can only be used if this is DeconstructionItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#get_tile_filter)
---@param index uint 
---@return string? 
get_tile_filter = function(index) end;
---Is this blueprint item setup? I.e. is it a non-empty blueprint?
---
---*Can only be used if this is BlueprintItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#is_blueprint_setup)
---@return boolean 
is_blueprint_setup = function() end;
---Removes a tag with the given name.
---
---*Can only be used if this is ItemWithTags*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#remove_tag)
---@param tag string 
---@return boolean  #If the tag existed and was removed.
remove_tag = function(tag) end;
---Set new entities to be a part of this blueprint.
---
---*Can only be used if this is BlueprintItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#set_blueprint_entities)
---@param entities (BlueprintEntity)[] The new blueprint entities.
set_blueprint_entities = function(entities) end;
---Sets the given tag on the given blueprint entity index in this blueprint item.
---
---*Can only be used if this is BlueprintItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#set_blueprint_entity_tag)
---@param index uint The entity index.
---@param tag string The tag to set.
---@param value AnyBasic The tag value to set or `nil` to clear the tag.
set_blueprint_entity_tag = function(index, tag, value) end;
---Sets the tags on the given blueprint entity index in this blueprint item.
---
---*Can only be used if this is BlueprintItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#set_blueprint_entity_tags)
---@param index uint The entity index
---@param tags Tags 
set_blueprint_entity_tags = function(index, tags) end;
---Set specific tiles in this blueprint.
---
---*Can only be used if this is BlueprintItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#set_blueprint_tiles)
---@param tiles (Tile)[] Tiles to be a part of the blueprint.
set_blueprint_tiles = function(tiles) end;
---Sets the entity filter at the given index for this deconstruction item.
---
---*Can only be used if this is DeconstructionItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#set_entity_filter)
---@param index uint 
---@param filter (string)|(LuaEntityPrototype)|(LuaEntity)|(nil) Writing `nil` removes the filter.
---@return boolean  #Whether the new filter was successfully set (meaning it was valid).
set_entity_filter = function(index, filter) end;
---Sets the module filter at the given index for this upgrade item.
---
---In contrast to [LuaItemCommon::get\_mapper](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#get_mapper), indices past the upgrade item's current size are valid and expand the list of mappings accordingly, if within reasonable bounds.
---
---*Can only be used if this is UpgradeItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#set_mapper)
---@param index uint The index of the mapper to set.
---@param type ("from")|("to") 
---@param mapper (UpgradeMapperSource)|(UpgradeMapperDestination)|(nil) The mapper to set or `nil`
set_mapper = function(index, type, mapper) end;
---Sets the tag with the given name and value.
---
---*Can only be used if this is ItemWithTags*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#set_tag)
---@param tag_name string 
---@param tag AnyBasic 
set_tag = function(tag_name, tag) end;
---Sets the tile filter at the given index for this deconstruction item.
---
---*Can only be used if this is DeconstructionItem*
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemCommon.html#set_tile_filter)
---@param index uint 
---@param filter (string)|(LuaTilePrototype)|(LuaTile)|(nil) Writing `nil` removes the filter.
---@return boolean  #Whether the new filter was successfully set (meaning it was valid).
set_tile_filter = function(index, filter) end;
}
end

