---@meta _

--$Factorio 2.1.20
--$Generator 1.1.47
--$Section runtime-api/LuaItemSubGroup
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Item subgroup.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemSubGroup.html)
---@class LuaItemSubGroup:LuaObject
---The parent group.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemSubGroup.html#group)
---@field group LuaItemGroup
---Localised name of the subgroup.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemSubGroup.html#localised_name)
---@field localised_name LocalisedString
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemSubGroup.html#name)
---@field name string
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemSubGroup.html#object_name)
---@field object_name string
---The string used to alphabetically sort these prototypes. It is a simple string that has no additional semantic meaning.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemSubGroup.html#order)
---@field order string
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemSubGroup.html#type)
---@field type string
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaItemSubGroup.html#valid)
---@field valid boolean
local LuaItemSubGroup={
}
end

