---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaLogisticContainerControlBehavior
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Control behavior for logistic chests.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticContainerControlBehavior.html)
---@class LuaLogisticContainerControlBehavior:LuaControlBehavior
---The circuit condition for the logistic container.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticContainerControlBehavior.html#circuit_condition)
---@field circuit_condition CircuitConditionDefinition
---Whether the circuit condition is in effect
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticContainerControlBehavior.html#circuit_condition_enabled)
---@field circuit_condition_enabled boolean
---The circuit mode of operations for the logistic container. Can only be set on containers whose [logistic\_mode](https://lua-api.factorio.com/latest/classes/LuaEntityPrototype.html#logistic_mode) is set to `"requester"` or `"buffer"`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticContainerControlBehavior.html#circuit_exclusive_mode_of_operation)
---@field circuit_exclusive_mode_of_operation defines.control_behavior.logistic_container.exclusive_mode
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticContainerControlBehavior.html#object_name)
---@field object_name string
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticContainerControlBehavior.html#valid)
---@field valid boolean
local LuaLogisticContainerControlBehavior={
}
end

