---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaLoaderControlBehavior
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Control behavior for loaders.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLoaderControlBehavior.html)
---@class LuaLoaderControlBehavior:LuaGenericOnOffControlBehavior
---`true` if the transfers between loader's belt and container should be pulsed to the circuit network
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLoaderControlBehavior.html#circuit_read_transfers)
---@field circuit_read_transfers boolean
---`true` if filters are set from circuit network
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLoaderControlBehavior.html#circuit_set_filters)
---@field circuit_set_filters boolean
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLoaderControlBehavior.html#object_name)
---@field object_name string
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLoaderControlBehavior.html#valid)
---@field valid boolean
local LuaLoaderControlBehavior={
}
end

