---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaLogisticPoint
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Logistic point of a particular [LuaEntity](https://lua-api.factorio.com/latest/classes/LuaEntity.html). A "Logistic point" is the name given for settings and properties used by requester, provider, and storage points in a given logistic network. These "points" don't have to be a logistic container but often are. One other entity that can own several points is the "character" character type entity.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html)
---@class LuaLogisticPoint:LuaObject
---Whether this logistic point is active, related to disabling logistics on player/spidertron.
---
---When the logistic point is disabled it won't request and auto trash will do nothing.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#enabled)
---@field enabled boolean
---If this logistic point is using the exact mode. In exact mode robots never over-deliver requests.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#exact)
---@field exact boolean
---The logistic filters for this logistic point, if this uses any.
---
---The returned array will always have an entry for each filter and will be indexed in sequence when not `nil`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#filters)
---@field filters? (CompiledLogisticFilter)[]
---The force of this logistic point.
---
---This will always be the same as the [LuaLogisticPoint::owner](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#owner) force.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#force)
---@field force LuaForce
---The Logistic member index of this logistic point.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#logistic_member_index)
---@field logistic_member_index uint
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#logistic_network)
---@field logistic_network LuaLogisticNetwork
---The logistic mode.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#mode)
---@field mode defines.logistic_mode
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#object_name)
---@field object_name string
---The [LuaEntity](https://lua-api.factorio.com/latest/classes/LuaEntity.html) owner of this LuaLogisticPoint.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#owner)
---@field owner LuaEntity
---All logistic sections of this logistic point.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#sections)
---@field sections (LuaLogisticSection)[]
---Amount of logistic sections this logistic point has.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#sections_count)
---@field sections_count uint
---Items targeted to be dropped off into this logistic point by robots. The attribute is a dictionary mapping the item prototype names to their item counts.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#targeted_items_deliver)
---@field targeted_items_deliver {[string]:uint}
---Items targeted to be picked up from this logistic point by robots. The attribute is a dictionary mapping the item prototype names to their item counts.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#targeted_items_pickup)
---@field targeted_items_pickup {[string]:uint}
---Whether this logistic point is set to trash unrequested items.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#trash_not_requested)
---@field trash_not_requested boolean
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#valid)
---@field valid boolean
local LuaLogisticPoint={
---Adds a new logistic section to this logistic point if possible.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#add_section)
---@param group? string The group to assign this section to.
---@return LuaLogisticSection?  #The added logistic section.
add_section = function(group) end;
---Gets section on the selected index, if it exists
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#get_section)
---@param section_index uint Index of the section
---@return LuaLogisticSection 
get_section = function(section_index) end;
---Removes the given logistic section if possible. Removal may fail if the section index is out of range or the section is not [manual](https://lua-api.factorio.com/latest/classes/LuaLogisticSection.html#is_manual).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticPoint.html#remove_section)
---@param section_index uint Index of the section
---@return boolean  #Whether section was removed.
remove_section = function(section_index) end;
}
end

