---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaLogisticNetwork
-- This file is automatically generated. Edits will be overwritten without warning.

do
---@class LuaLogisticNetwork.select_drop_point_param
---Name of the item to drop off.
---@field stack ItemStackIdentification
---When given, it will find from only the specific type of member. If not specified, selects with normal priorities.
---@field members? ("storage")|("storage-empty")|("storage-empty-slot")|("requester")
local LuaLogisticNetwork_select_drop_point_param={
}
end

do
---@class LuaLogisticNetwork.select_pickup_point_param
---Name of the item to pick up.
---@field name ItemWithQualityID
---When given, it will find the storage 'best' storage point from this position.
---@field position? MapPosition
---Whether to consider buffer chests or not. Defaults to false. Only considered if selecting with position.
---@field include_buffers? boolean
---When given, it will find from only the specific type of member. If not specified, selects with normal priorities. Not considered if position is specified.
---@field members? ("active-provider")|("passive-provider")|("buffer")|("storage")
local LuaLogisticNetwork_select_pickup_point_param={
}
end

do
---A single logistic network of a given force on a given surface.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html)
---@class LuaLogisticNetwork:LuaObject
---All active provider points in this network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#active_provider_points)
---@field active_provider_points (LuaLogisticPoint)[]
---The total number of construction robots in the network (idle and active + in roboports).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#all_construction_robots)
---@field all_construction_robots uint
---The total number of logistic robots in the network (idle and active + in roboports).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#all_logistic_robots)
---@field all_logistic_robots uint
---Number of construction robots available for a job.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#available_construction_robots)
---@field available_construction_robots uint
---Number of logistic robots available for a job.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#available_logistic_robots)
---@field available_logistic_robots uint
---All cells in this network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#cells)
---@field cells (LuaLogisticCell)[]
---All construction robots in this logistic network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#construction_robots)
---@field construction_robots (LuaEntity)[]
---All things that have empty provider points in this network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#empty_provider_points)
---@field empty_provider_points (LuaLogisticPoint)[]
---All entities that have empty logistic provider points in this network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#empty_providers)
---@field empty_providers (LuaEntity)[]
---The force this logistic network belongs to.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#force)
---@field force LuaForce
---All other entities that have logistic points in this network (inserters mostly).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#logistic_members)
---@field logistic_members (LuaEntity)[]
---All logistic robots in this logistic network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#logistic_robots)
---@field logistic_robots (LuaEntity)[]
---The unique logistic network ID.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#network_id)
---@field network_id uint
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#object_name)
---@field object_name string
---All passive provider points in this network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#passive_provider_points)
---@field passive_provider_points (LuaLogisticPoint)[]
---All things that have provider points in this network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#provider_points)
---@field provider_points (LuaLogisticPoint)[]
---All entities that have logistic provider points in this network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#providers)
---@field providers (LuaEntity)[]
---All things that have requester points in this network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#requester_points)
---@field requester_points (LuaLogisticPoint)[]
---All entities that have logistic requester points in this network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#requesters)
---@field requesters (LuaEntity)[]
---Maximum number of robots the network can work with. Currently only used for the personal roboport.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#robot_limit)
---@field robot_limit uint
---All robots in this logistic network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#robots)
---@field robots (LuaEntity)[]
---All things that have storage points in this network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#storage_points)
---@field storage_points (LuaLogisticPoint)[]
---All entities that have logistic storage points in this network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#storages)
---@field storages (LuaEntity)[]
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#valid)
---@field valid boolean
local LuaLogisticNetwork={
---Can the network satisfy a request for a given item and count.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#can_satisfy_request)
---@param item ItemWithQualityID Item name to check.
---@param count? uint Count to check. Defaults to 1.
---@param include_buffers? boolean Should buffers be considered? Defaults to false.
---@return boolean  #Whether the network can satisfy the request.
can_satisfy_request = function(item, count, include_buffers) end;
---Find logistic cell closest to a given position.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#find_cell_closest_to)
---@param position MapPosition 
---@return LuaLogisticCell?  #`nil` if no cell was found.
find_cell_closest_to = function(position) end;
---Get item counts for the entire network, similar to how [LuaInventory::get\_contents](https://lua-api.factorio.com/latest/classes/LuaInventory.html#get_contents) does.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#get_contents)
---@return (ItemCountWithQuality)[]  #List of all items in the network.
get_contents = function() end;
---Count given or all items in the network or given members.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#get_item_count)
---@param item? ItemWithQualityID Item name to count. If not given, gives counts of all items in the network.
---@param member? ("storage")|("providers") Logistic members to check. If not given, gives count in the entire network.
---@return int 
get_item_count = function(item, member) end;
---Get the amount of items of the given type indexed by the storage member.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#get_supply_counts)
---@param item ItemWithQualityID Item name to check.
---@return LogisticsNetworkSupplyCounts 
get_supply_counts = function(item) end;
---Gets the logistic points with of the given type indexed by the storage member.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#get_supply_points)
---@param item ItemWithQualityID Item name to check.
---@return LogisticsNetworkSupplyPoints 
get_supply_points = function(item) end;
---Insert items into the logistic network. This will actually insert the items into some logistic chests.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#insert)
---@param item ItemStackIdentification What to insert.
---@param members? ("storage")|("storage-empty")|("storage-empty-slot")|("requester") Which logistic members to insert the items to. `"storage-empty"` inserts into storage chests that are completely empty, `"storage-empty-slot"` inserts into storage chests that have an empty slot. If not specified, inserts items into the logistic network in the usual order.
---@return uint  #Number of items actually inserted.
insert = function(item, members) end;
---Remove items from the logistic network. This will actually remove the items from some logistic chests.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#remove_item)
---@param item ItemStackIdentification What to remove.
---@param members? ("active-provider")|("passive-provider")|("buffer")|("storage") Which logistic members to remove from. If not specified, removes from the network in the usual order.
---@return uint  #Number of items removed.
remove_item = function(item, members) end;
---Find a logistic point to drop the specific item stack.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#select_drop_point)
---@param param LuaLogisticNetwork.select_drop_point_param 
---@return LuaLogisticPoint?  #`nil` if no point was found.
select_drop_point = function(param) end;
---Find the 'best' logistic point with this item ID and from the given position or from given chest type.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticNetwork.html#select_pickup_point)
---@param param LuaLogisticNetwork.select_pickup_point_param 
---@return LuaLogisticPoint?  #`nil` if no point was found.
select_pickup_point = function(param) end;
}
end

