---@meta _

--$Factorio 2.1.20
--$Generator 1.1.47
--$Section runtime-api/LuaLogisticSections
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Logistic sections of an entity.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticSections.html)
---@class LuaLogisticSections:LuaObject
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticSections.html#object_name)
---@field object_name string
---All logistic sections of this entity.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticSections.html#sections)
---@field sections (LuaLogisticSection)[]
---Amount of logistic sections this entity has.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticSections.html#sections_count)
---@field sections_count uint32
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticSections.html#valid)
---@field valid boolean
local LuaLogisticSections={
---Adds a new logistic section if possible.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticSections.html#add_section)
---@param group? string The group to assign this section to.
---@return LuaLogisticSection?  #Logistic section if added.
add_section = function(group) end;
---Gets section on the selected index, if it exists.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticSections.html#get_section)
---@param section_index LogisticSectionIndex Index of the section.
---@return LuaLogisticSection? 
get_section = function(section_index) end;
---Removes the given logistic section if possible. Removal may fail if the section index is out of range or the section is not [manual](https://lua-api.factorio.com/latest/classes/LuaLogisticSection.html#is_manual).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaLogisticSections.html#remove_section)
---@param section_index LogisticSectionIndex Index of the section.
---@return boolean  #Whether section was removed.
remove_section = function(section_index) end;
}
end

