---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaModSettingPrototype
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Prototype of a mod setting.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaModSettingPrototype.html)
---@class LuaModSettingPrototype:LuaPrototypeBase
---Whether this string setting allows blank values. `nil` if not a string setting.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaModSettingPrototype.html#allow_blank)
---@field allow_blank? boolean
---The allowed values for this setting. `nil` if this setting doesn't use the a fixed set of values.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaModSettingPrototype.html#allowed_values)
---@field allowed_values? ((string)[])|((int)[])|((double)[])
---Whether this string setting auto-trims values. `nil` if not a string setting
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaModSettingPrototype.html#auto_trim)
---@field auto_trim? boolean
---The default value of this setting.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaModSettingPrototype.html#default_value)
---@field default_value (boolean)|(double)|(int)|(string)|(Color)
---The maximum value for this setting. `nil` if this setting type doesn't support a maximum.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaModSettingPrototype.html#maximum_value)
---@field maximum_value? (double)|(int)
---The minimum value for this setting. `nil` if this setting type doesn't support a minimum.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaModSettingPrototype.html#minimum_value)
---@field minimum_value? (double)|(int)
---The mod that owns this setting.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaModSettingPrototype.html#mod)
---@field mod string
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaModSettingPrototype.html#object_name)
---@field object_name string
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaModSettingPrototype.html#setting_type)
---@field setting_type ("startup")|("runtime-global")|("runtime-per-user")
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaModSettingPrototype.html#valid)
---@field valid boolean
local LuaModSettingPrototype={
}
end

