---@meta _

--$Factorio 2.1.20
--$Generator 1.1.47
--$Section runtime-api/LuaNotificationQueue
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Object that keeps track of objects invalidation and queues notifications for when object becomes invalid.
---
---This object is an alternative mechanism to [LuaBootstrap::register\_on\_object\_destroyed](https://lua-api.factorio.com/latest/classes/LuaBootstrap.html#register_on_object_destroyed) where instead of raising lua events, this object only queues notifications and makes them available to use later by calls to [LuaNotificationQueue::poll](https://lua-api.factorio.com/latest/classes/LuaNotificationQueue.html#poll) or [LuaNotificationQueue::poll\_all](https://lua-api.factorio.com/latest/classes/LuaNotificationQueue.html#poll_all).
---
---New instances of this object can be obtained from [LuaBootstrap::new\_notification\_queue](https://lua-api.factorio.com/latest/classes/LuaBootstrap.html#new_notification_queue).
---
---Each instance of this object is unique, always valid and cannot be copied. This object lives entirely in script state and if its no longer referenced by script, it will be destroyed by garbage collector.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaNotificationQueue.html)
---@class LuaNotificationQueue:LuaObject
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaNotificationQueue.html#object_name)
---@field object_name string
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaNotificationQueue.html#valid)
---@field valid boolean
local LuaNotificationQueue={
---Registers an object so that after it's destroyed, a notification is queued.
---
---If this object is already registered within this notification queue, an existing registration number will be provided without creating new registration.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaNotificationQueue.html#add)
---@param object RegistrationTarget The object to register.
---@return uint64  #The registration number.
add = function(object) end;
---Removes all registrations.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaNotificationQueue.html#clear)
clear = function() end;
---Checks if provided object is already registered and returns existing registration number for it. If object is not registered, it is not registered and nil is returned instead.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaNotificationQueue.html#find)
---@param object RegistrationTarget The object to check.
---@return uint64?  #The registration number if object is registered.
find = function(object) end;
---Gets at most 1 registration id for which an object was destroyed.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaNotificationQueue.html#poll)
---@return uint64? 
poll = function() end;
---Gets all registration ids for which object were destroyed.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaNotificationQueue.html#poll_all)
---@return (uint64)[] 
poll_all = function() end;
---Removes a registration based on registration number.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaNotificationQueue.html#remove)
---@param registration_id uint64 Registration to be removed.
remove = function(registration_id) end;
}
end

