---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaPermissionGroup
-- This file is automatically generated. Edits will be overwritten without warning.

do
---A permission group that defines what players in this group are allowed to do.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPermissionGroup.html)
---@class LuaPermissionGroup:LuaObject
---The group ID
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPermissionGroup.html#group_id)
---@field group_id uint
---The name of this group. Setting the name to `nil` or an empty string sets the name to the default value.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPermissionGroup.html#name)
---@field name string
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPermissionGroup.html#object_name)
---@field object_name string
---The players in this group.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPermissionGroup.html#players)
---@field players (LuaPlayer)[]
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPermissionGroup.html#valid)
---@field valid boolean
local LuaPermissionGroup={
---Adds the given player to this group.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPermissionGroup.html#add_player)
---@param player PlayerIdentification 
---@return boolean  #Whether the player was added.
add_player = function(player) end;
---Whether this group allows the given action.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPermissionGroup.html#allows_action)
---@param action defines.input_action The action in question.
---@return boolean 
allows_action = function(action) end;
---Destroys this group.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPermissionGroup.html#destroy)
---@return boolean  #Whether the group was successfully destroyed.
destroy = function() end;
---Removes the given player from this group.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPermissionGroup.html#remove_player)
---@param player PlayerIdentification 
---@return boolean  #Whether the player was removed.
remove_player = function(player) end;
---Sets whether this group allows the performance the given action.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPermissionGroup.html#set_allows_action)
---@param action defines.input_action The action in question.
---@param allow_action boolean Whether to allow the specified action.
---@return boolean  #Whether the value was successfully applied.
set_allows_action = function(action, allow_action) end;
}
end

