---@meta _

--$Factorio 2.1.20
--$Generator 1.1.47
--$Section runtime-api/LuaPin
-- This file is automatically generated. Edits will be overwritten without warning.

do
---A pin owned by a player.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html)
---@class LuaPin:LuaObject
---The alert positions if this pin is configured to show alert data.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html#alert_positions)
---@field alert_positions (MapPosition)[]
---The type of alert this pin is for (if configured to be about alerts).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html#alert_type)
---@field alert_type? defines.alert_type
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html#always_visible)
---@field always_visible boolean
---The custom chart tag - if this pin specificaly binds to a chart tag.
---
---The chart tag must be on the same force as the owning player.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html#chart_tag)
---@field chart_tag? LuaCustomChartTag
---The index of this pin (unique to this player).
---
---Note that this index has no corelation to the position of the pin within [LuaPlayer::get\_pins](https://lua-api.factorio.com/latest/classes/LuaPlayer.html#get_pins)
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html#index)
---@field index uint32
---The label for this pin - if any. This will be an empty string if there is no label set.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html#label)
---@field label string
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html#object_name)
---@field object_name string
---The player that this pin belongs to.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html#owner)
---@field owner LuaPlayer
---The player that this pin is bound to.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html#player)
---@field player? LuaPlayer
---The position if this pin specifically binds to a surface and position.
---
---If writing, and this pin was not bound to a specific surface and position, the default surface of nauvis is used.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html#position)
---@field position? MapPosition
---The radius (in tiles) that is shown in the tooltip for this pin.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html#preview_distance)
---@field preview_distance uint16
---The surface index if this pin specifically binds to a surface and position.
---
---If writing, and this pin was not bound to a specific surface and position, the default position of (0,0) is used.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html#surface_index)
---@field surface_index? uint32
---The targets of this pin - if any.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html#targets)
---@field targets (LuaEntity)[]
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html#valid)
---@field valid boolean
local LuaPin={
---Destroys this pin.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html#destroy)
destroy = function() end;
---The center of this pin if it can be computed.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPin.html#get_pin_center)
---@return MapPosition? 
get_pin_center = function() end;
}
end

