---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaPrototypeBase
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Base for all prototype classes.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPrototypeBase.html)
---@class LuaPrototypeBase:LuaObject
---Group of this prototype.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPrototypeBase.html#group)
---@field group LuaGroup
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPrototypeBase.html#hidden)
---@field hidden boolean
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPrototypeBase.html#hidden_in_factoriopedia)
---@field hidden_in_factoriopedia boolean
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPrototypeBase.html#localised_description)
---@field localised_description LocalisedString
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPrototypeBase.html#localised_name)
---@field localised_name LocalisedString
---Name of this prototype.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPrototypeBase.html#name)
---@field name string
---The string used to alphabetically sort these prototypes. It is a simple string that has no additional semantic meaning.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPrototypeBase.html#order)
---@field order string
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPrototypeBase.html#parameter)
---@field parameter boolean
---Subgroup of this prototype.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPrototypeBase.html#subgroup)
---@field subgroup LuaGroup
---Type of this prototype.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPrototypeBase.html#type)
---@field type string
local LuaPrototypeBase={
}
end

