---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaPlanet
-- This file is automatically generated. Edits will be overwritten without warning.

do
---The runtime values of a planet
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPlanet.html)
---@class LuaPlanet:LuaObject
---The planets name.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPlanet.html#name)
---@field name string
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPlanet.html#object_name)
---@field object_name string
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPlanet.html#prototype)
---@field prototype LuaSpaceLocationPrototype
---The surface for this planet if one currently exists.
---
---Planets do not default generate their surface. [LuaPlanet::create\_surface](https://lua-api.factorio.com/latest/classes/LuaPlanet.html#create_surface) can be used to force the surface to exist.
---
---[LuaPlanet::associate\_surface](https://lua-api.factorio.com/latest/classes/LuaPlanet.html#associate_surface) can be used to create an association with an existing surface.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPlanet.html#surface)
---@field surface LuaSurface
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPlanet.html#valid)
---@field valid boolean
local LuaPlanet={
---Associates the given surface with this planet. Surface must not already be associated with a planet and the planet must not already have an associated surface.
---
---Planet must not be using [entities\_require\_heating](https://lua-api.factorio.com/latest/classes/LuaSpaceLocationPrototype.html#entities_require_heating).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPlanet.html#associate_surface)
---@param surface SurfaceIdentification The surface to be associated.
associate_surface = function(surface) end;
---Creates the associated surface if one doesn't already exist.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPlanet.html#create_surface)
---@return LuaSurface 
create_surface = function() end;
---Resets the map gen settings on this planet to the default from-prototype state.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaPlanet.html#reset_map_gen_settings)
reset_map_gen_settings = function() end;
}
end

