---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaReactorControlBehavior
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Control behavior for Reactor
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaReactorControlBehavior.html)
---@class LuaReactorControlBehavior:LuaControlBehavior
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaReactorControlBehavior.html#object_name)
---@field object_name string
---If this will read fuel inventory and currently burning fuel
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaReactorControlBehavior.html#read_fuel)
---@field read_fuel boolean
---If this will read temperature of the reactor
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaReactorControlBehavior.html#read_temperature)
---@field read_temperature boolean
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaReactorControlBehavior.html#temperature_signal)
---@field temperature_signal? SignalID
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaReactorControlBehavior.html#valid)
---@field valid boolean
local LuaReactorControlBehavior={
}
end

