---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaRocketSiloControlBehavior
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Control behavior for rocket silos.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaRocketSiloControlBehavior.html)
---@class LuaRocketSiloControlBehavior:LuaControlBehavior
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaRocketSiloControlBehavior.html#object_name)
---@field object_name string
---The items read mode for the rocket silo.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaRocketSiloControlBehavior.html#read_mode)
---@field read_mode defines.control_behavior.rocket_silo.read_mode
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaRocketSiloControlBehavior.html#valid)
---@field valid boolean
local LuaRocketSiloControlBehavior={
}
end

