---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaRCON
-- This file is automatically generated. Edits will be overwritten without warning.

do
---An interface to send messages to the calling RCON interface through the global object named `rcon`.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaRCON.html)
---@class LuaRCON:LuaObject
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaRCON.html#object_name)
---@field object_name string
rcon={
---Print text to the calling RCON interface if any.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaRCON.html#print)
---@param message LocalisedString 
print = function(message) end;
}
end

