---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaSpaceLocationPrototype
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Prototype of a space location, such as a planet.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSpaceLocationPrototype.html)
---@class LuaSpaceLocationPrototype:LuaPrototypeBase
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSpaceLocationPrototype.html#asteroid_spawn_definitions)
---@field asteroid_spawn_definitions? (SpaceLocationAsteroidSpawnDefinition)[]
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSpaceLocationPrototype.html#asteroid_spawn_influence)
---@field asteroid_spawn_influence double
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSpaceLocationPrototype.html#entities_require_heating)
---
---*Can only be used if this is Planet*
---@field entities_require_heating? boolean
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSpaceLocationPrototype.html#map_gen_settings)
---
---*Can only be used if this is Planet*
---@field map_gen_settings? MapGenSettings
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSpaceLocationPrototype.html#map_seed_offset)
---
---*Can only be used if this is Planet*
---@field map_seed_offset? uint
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSpaceLocationPrototype.html#object_name)
---@field object_name string
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSpaceLocationPrototype.html#player_effects)
---
---*Can only be used if this is Planet*
---@field player_effects? (TriggerItem)[]
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSpaceLocationPrototype.html#pollutant_type)
---
---*Can only be used if this is Planet*
---@field pollutant_type? LuaAirbornePollutantPrototype
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSpaceLocationPrototype.html#position)
---@field position MapPosition
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSpaceLocationPrototype.html#solar_power_in_space)
---@field solar_power_in_space double
---A mapping of the surface property name to the value.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSpaceLocationPrototype.html#surface_properties)
---
---*Can only be used if this is Planet*
---@field surface_properties? {[string]:double}
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSpaceLocationPrototype.html#ticks_between_player_effects)
---
---*Can only be used if this is Planet*
---@field ticks_between_player_effects? uint
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSpaceLocationPrototype.html#valid)
---@field valid boolean
local LuaSpaceLocationPrototype={
}
end

