---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaSelectorCombinatorControlBehavior
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Control behavior for selector combinators.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSelectorCombinatorControlBehavior.html)
---@class LuaSelectorCombinatorControlBehavior:LuaCombinatorControlBehavior
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSelectorCombinatorControlBehavior.html#object_name)
---@field object_name string
---The selector combinator parameters. `parameters` may be `nil` in order to clear the parameters.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSelectorCombinatorControlBehavior.html#parameters)
---@field parameters SelectorCombinatorParameters
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSelectorCombinatorControlBehavior.html#valid)
---@field valid boolean
local LuaSelectorCombinatorControlBehavior={
}
end

