---@meta _

--$Factorio 2.1.20
--$Generator 1.1.47
--$Section runtime-api/LuaSingleFluidBoxControlBehavior
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Control behavior for entities with a single fluid box (i.e. pipe, pipe-to-ground, storage-tank).
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSingleFluidBoxControlBehavior.html)
---@class LuaSingleFluidBoxControlBehavior:LuaControlBehavior
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSingleFluidBoxControlBehavior.html#circuit_exclusive_mode_of_operation)
---@field circuit_exclusive_mode_of_operation defines.control_behavior.single_fluid_box.exclusive_mode
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSingleFluidBoxControlBehavior.html#object_name)
---@field object_name string
---If this will read the temperature of the fluid.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSingleFluidBoxControlBehavior.html#read_temperature)
---@field read_temperature boolean
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSingleFluidBoxControlBehavior.html#temperature_signal)
---@field temperature_signal? SignalID
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaSingleFluidBoxControlBehavior.html#valid)
---@field valid boolean
local LuaSingleFluidBoxControlBehavior={
}
end

