---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaTransportBeltControlBehavior
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Control behavior for transport belts.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTransportBeltControlBehavior.html)
---@class LuaTransportBeltControlBehavior:LuaGenericOnOffControlBehavior
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTransportBeltControlBehavior.html#object_name)
---@field object_name string
---If the belt will read the contents and send them to the circuit network.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTransportBeltControlBehavior.html#read_contents)
---@field read_contents boolean
---The read mode for the belt.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTransportBeltControlBehavior.html#read_contents_mode)
---@field read_contents_mode defines.control_behavior.transport_belt.content_read_mode
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTransportBeltControlBehavior.html#valid)
---@field valid boolean
local LuaTransportBeltControlBehavior={
}
end

