---@meta _

--$Factorio 2.0.9
--$Generator 1.1.47
--$Section runtime-api/LuaTrivialSmokePrototype
-- This file is automatically generated. Edits will be overwritten without warning.

do
---Prototype of a trivial smoke.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html)
---@class LuaTrivialSmokePrototype:LuaPrototypeBase
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html#affected_by_wind)
---@field affected_by_wind boolean
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html#color)
---@field color Color
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html#cyclic)
---@field cyclic boolean
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html#duration)
---@field duration uint
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html#end_scale)
---@field end_scale double
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html#fade_away_duration)
---@field fade_away_duration uint
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html#fade_in_duration)
---@field fade_in_duration uint
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html#glow_animation)
---@field glow_animation boolean
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html#glow_fade_away_duration)
---@field glow_fade_away_duration uint
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html#movement_slow_down_factor)
---@field movement_slow_down_factor double
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html#object_name)
---@field object_name string
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html#render_layer)
---@field render_layer RenderLayer
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html#show_when_smoke_off)
---@field show_when_smoke_off boolean
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html#spread_duration)
---@field spread_duration uint
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html#start_scale)
---@field start_scale double
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View Documentation](https://lua-api.factorio.com/latest/classes/LuaTrivialSmokePrototype.html#valid)
---@field valid boolean
local LuaTrivialSmokePrototype={
}
end

